#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Parse an Aerial GPU Benchmark nsys-rep into per-channel kernel latency.

Approach (context + static cuPHY kernel map)
--------------------------------------------
Each channel group runs in its own CUDA context (the MPS sub-contexts from the
``*_isolate`` flags, or green contexts). We group kernels by **context**
(``contextId`` for MPS, ``greenContextId`` for green contexts — auto-detected),
then **label each context by its dominant channel** using a static kernel ->
channel map (``_CHANNEL_KERNELS``) derived from the cuPHY source tree.

The map is built from the ``__global__`` kernel definitions under ``cuPHY/src``:
each kernel defined in a **channel-specific** directory (e.g.
``cuphy/channel_eq`` -> PUSCH, ``cuphy/pdcch`` -> PDCCH, ``cuphy/csirs`` ->
CSI-RS, ``cuphy_channels/pusch_rx`` -> PUSCH, …) is listed below. Kernels from
**shared** function dirs (LDPC, CRC, rate-matching, polar, scrambling, …) are
recognized as ``shared`` and attributed to whichever context they run in (the
context resolves the channel; their name alone can't). Kernels that are neither
(test-bench timing / graph / wait kernels) are ``infra`` and excluded.

Each context becomes ONE channel report, labeled by the channel-specific kernels
that dominate its busy time. For the CICD cases that is exactly five reports:
PDSCH, PUSCH, PUCCH, PDCCH, PRACH (PDCCH and CSI-RS share a context by design;
the context is labeled by its dominant channel and the CSI-RS kernels are shown
within it). The pure timing/anchor context is dropped.

Latency only
------------
nsys has no FLOP counters, so this emits latency only (CUPTI kernel durations).
Within a channel, kernels are grouped by name into an array giving both the
aggregate latency (count + mean/min/max/p50/p90/p99) and the separate
per-instance durations (``instances_us``). Per-kernel latency is GPU busy time;
it is not the channel's end-to-end (event-based) latency the dashboard's latency
panel shows.

Classification: include-by-default, blacklist the infra
--------------------------------------------------------
Every kernel is MEANINGFUL and kept unless it matches the infra blacklist
(``_INFRA_PREFIXES``: timing/pacing, graph machinery, generic data movement).
A brand-new cuPHY kernel therefore shows up on the dashboard by default —
the failure mode of an out-of-date map is visible noise, never invisible loss.

The channel a kept kernel is attributed to is resolved by the first match of:

1. exact short name in ``_CHANNEL_KERNELS`` (a trailing version suffix such as
   ``_v3`` / ``V2`` is stripped first, so ``fusedPdcchTxKernelV0/V1/V2/...`` all
   resolve via one ``fusedPdcchTxKernel`` entry);
2. the C++ **namespace** of the demangled name via ``_NAMESPACE2CHANNEL``
   (e.g. ``embedPdcchTx::`` -> PDCCH, ``csirsTf::`` -> CSI-RS) — this is what
   makes future kernels added inside an existing channel namespace work without
   touching this file;
3. cuMAC name patterns (``_MAC_NAME_PREFIXES`` / ``_MAC_NAME_SUBSTRINGS``) ->
   MAC. The cuMAC workload is a TensorRT MLP engine, and TRT/Myelin kernel
   names are engine-build-specific (arch, tactic, hash), so they match by
   pattern rather than exact name. Must run before the infra blacklist, whose
   ``__`` prefix would swallow the Myelin ``__myl_*`` kernels;
4. ``_SHARED_PREFIXES`` (LDPC/CRC/polar/... function-library kernels) ->
   ``(shared)``, attributed to their context's channel;
5. the infra blacklist (``_INFRA_PREFIXES``) -> ``(infra)``, excluded;
6. otherwise ``(unclassified)``: KEPT in its context's kernel list exactly like
   ``(shared)``, and a warning listing the names is printed to stderr as a
   prompt to either add a channel mapping or a blacklist entry. Neither
   ``(shared)`` nor ``(unclassified)`` kernels vote when labeling a context by
   its dominant channel.

Regenerating the static map
---------------------------
``_CHANNEL_KERNELS`` was generated by scanning ``cuPHY/src`` for ``__global__``
definitions and mapping each kernel's defining directory to a channel. If cuPHY
adds/renames channel kernels, re-scan and update the sets below (or extend
``_NAMESPACE2CHANNEL`` — preferred, it covers whole families at once).

Usage
-----
    python3 nsys_parser.py run.nsys-rep -o kernels.json   # needs `nsys` on PATH
    python3 nsys_parser.py run.sqlite   -o kernels.json   # pre-exported sqlite
"""

from __future__ import annotations

import argparse
import json
import math
import re
import shutil
import sqlite3
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

# ─────────────────────────── static cuPHY kernel map ───────────────────────────
# Channel-specific kernels (defined in a channel-specific cuPHY dir). Names are
# the nsys short names (template/version suffix `_vN` is stripped before lookup).
# Used to LABEL a context by its dominant channel. Generated from cuPHY/src.
_CHANNEL_KERNELS: dict[str, set[str]] = {
    "PUSCH": {
        "bluestein_Idft_kernel", "bluestein_workspace_kernel", "cfoTaEstLowMimoKernel",
        "chEstFilterNoDftSOfdmDispatchKernel", "chEstFilterPrgNoDftSOfdmDispatchKernel",
        "eqMmseCoefCompHighMimoKernel", "eqMmseCoefCompLowMimoKernel",
        "eqMmseCoefCompMassiveMimoKernel", "eqMmseEqualizationKernel",
        "eqMmseSoftDemap72eKernel",
        "eqMmseSoftDemapAfterDftKernel", "eqMmseSoftDemapKernel",
        "eqMmseSoftDemapKernel_64R", "extractChestMlOutputsKernel",
        "mmse_1D_time_frequency_kernel", "noiseIntfEstKernel",
        "noiseIntfEstNoDftSOfdmKernel", "prepareChestMlInputsKernel",
        "puschRkhsChEstKernel", "rsrpMeasKernel", "rsrpMeasWithoutPostEqMeasKernel",
        "rssiMeasKernel", "sinrMeasEarlyHarqKernel", "smallChEstKernel",
        "smallChEstNoDftSOfdmKernel", "soft_demapper_kernel", "uciOnPuschCsi2CtrlKernel",
        "uciOnPuschSegLLRs0Kernel", "uciOnPuschSegLLRs1Kernel", "uciOnPuschSegLLRs2Kernel",
        "windowedChEstKernel", "windowedChEstNoDftSOfdmKernel",
        "windowedChEstPreNoDftSOfdmKernel",
    },
    "PDSCH": {
        "dl_rate_matching", "fused_dl_rm_and_modulation", "fused_dl_rm_and_modulation_fast",
        "fused_dmrs", "genCsirsReMap",
        "modulation_mapper", "postProcessCsirsReMap", "restructure_rate_matching_output",
        "sym_mod_util", "zero_memset_kernel",
    },
    "PUCCH": {
        "pucchF0RxKernel", "pucchF1RxKernel", "pucchF234UciSegKernel", "pucchF2RxKernel",
        "pucchF3Csi2CtrlKernel", "pucchF3RxKernel", "pucchF3SegLLRsKernel",
    },
    "PDCCH": {
        "genPdcchTfSignalKernel",
        # fused single-kernel pipeline (encode + scramble + TF embed); a trailing
        # version suffix (e.g. V2) would be stripped by _norm, so this entry also
        # covers any future versioned variants.
        "fusedPdcchTxKernel",
    },
    "CSI-RS": {
        "csirsRxChEstKernel", "genCsirsTfSignalKernel",
    },
    "PRACH": {
        "block_fft_kernel", "memcpyRssi", "memsetRssi", "prach_compute_correlation",
        "prach_compute_pdp", "prach_compute_rssi", "prach_search_pdp",
    },
    "SRS": {
        "genSrsTx", "srsChEstKernel", "srsChEstNormalizationKernel",
        "srsChEstNormalizationLinearAlgo1Kernel", "srsRkhsChEstKernel",
    },
}

# Shared cuPHY kernels (LDPC, CRC, rate-matching, polar, scrambling, RNG, BFW…)
# live in function dirs used by multiple channels. Recognized as `shared` (so
# they're kept, not treated as infra) and attributed to their context's channel.
# Matched as lowercase prefixes — covers the many templated LDPC variants.
_SHARED_PREFIXES = (
    "ldpc", "crc", "de_rate_matching", "descramble", "encoderatematch",
    "genscrambling", "polar", "polseg", "listpolar", "simplex_decoder",
    "compcwtree", "prepare_crc", "rm_decoder", "pucch_rm_decoder",
    "pucch_common", "pucch_fused", "qam_to_bits", "tensor_rng", "cuphy_rng",
    "bfw", "bfc", "ssbmod",
)

INFRA = "(infra)"
SHARED = "(shared)"
UNCLASSIFIED = "(unclassified)"

# C++ namespace (lowercased, from the demangled name) -> channel. Preferred
# extension point: a new kernel inside one of these namespaces is attributed
# automatically, with no per-kernel entry needed.
_NAMESPACE2CHANNEL: dict[str, str] = {
    "embedpdcchtx":   "PDCCH",
    "csirstf":        "CSI-RS",
    "polar_encoder":  SHARED,   # PDCCH/PBCH/SSB polar encode + rate match
    "descrambling":   SHARED,   # gold sequence helpers
    "genericreformat": "MAC",   # TensorRT input/output cast kernels (cuMAC MLP)
}

# cuMAC (TensorRT MLP engine) kernel-name patterns. TRT kernel names embed the
# arch/tactic (sm80_xmma_gemm_..._execute_kernel_trt) and Myelin fused kernels
# embed an engine-build hash (__myl_<Ops>_<hash>_vec), so exact-name entries
# would break on every engine rebuild or GPU change — match by pattern instead.
# Verified against real GH200 traces: these patterns hit every kernel in the
# MAC green context and none in any PHY context. Checked before
# _SHARED_PREFIXES/_INFRA_PREFIXES ("__" infra would swallow "__myl*").
_MAC_NAME_PREFIXES = ("__myl", "sm80_xmma", "sm90_xmma")
_MAC_NAME_SUBSTRINGS = ("_kernel_trt",)

# Infra BLACKLIST: test-bench timing / graph machinery / generic data-movement
# kernels, excluded from reports entirely. Everything NOT matched here (and not
# a channel kernel) is treated as meaningful and kept, so a brand-new cuPHY
# kernel can never silently vanish from the dashboard — the failure mode of a
# missing blacklist entry is visible noise, not invisible data loss.
# Matched as lowercase prefixes on the (suffix-stripped) short name.
# NB: checked AFTER the exact channel map, so exact entries like PRACH's
# memcpyRssi/memsetRssi keep their channel despite the memcpy/memset prefixes.
_INFRA_PREFIXES = (
    # test-bench timing / pacing
    "delay", "gpu_us_delay", "get_ptimer", "loop_kernel", "snapshot_ptp",
    "symbolwait", "wait",
    # CUDA-graph machinery / placeholders
    "graphs_empty", "empty", "dummy", "devicegraphlaunch",
    "kdevicegraphlauncher", "kcondsethandle",
    # generic data movement / conversion utilities (cuphy root dir)
    "convert_", "copykernel", "tensor_fill", "memset", "memcpy",
    # library-internal kernels
    "vectorized_", "cub", "thrust", "__",
)

# name (lowercased) -> channel, built from _CHANNEL_KERNELS at import.
_NAME2CHANNEL: dict[str, str] = {}
for _ch, _names in _CHANNEL_KERNELS.items():
    for _n in _names:
        _NAME2CHANNEL[_n.lower()] = _ch

# Strip a trailing version suffix: `_v3` (template/version) or a bare `V2`
# variant marker as in fusedPdcchTxKernelV2 (matched after lowercasing).
_VSUFFIX_RE = re.compile(r"_?v\d+$")

_NAMESPACE_RE = re.compile(r"([A-Za-z_][A-Za-z0-9_]*)::")


def _norm(name: str) -> str:
    """Lowercase + strip a trailing template/version suffix (e.g. _v4, V2)."""
    return _VSUFFIX_RE.sub("", (name or "").lower())


def _namespace_of(demangled: str | None) -> str | None:
    """First C++ namespace of a demangled kernel name, lowercased (or None)."""
    if not demangled:
        return None
    m = _NAMESPACE_RE.search(demangled.split("(", 1)[0])
    return m.group(1).lower() if m else None


def classify(short_name: str, demangled: str | None = None) -> str:
    """Channel (PUSCH/…), SHARED, INFRA or UNCLASSIFIED for a kernel name.

    Layers, first match wins: exact short-name map -> namespace map (needs the
    demangled name) -> shared prefixes -> infra prefixes -> UNCLASSIFIED.
    """
    low = _norm(short_name)
    ch = _NAME2CHANNEL.get(low)
    if ch:
        return ch
    ns = _namespace_of(demangled)
    if ns and ns in _NAMESPACE2CHANNEL:
        return _NAMESPACE2CHANNEL[ns]
    if low.startswith(_MAC_NAME_PREFIXES) or \
            any(s in low for s in _MAC_NAME_SUBSTRINGS):
        return "MAC"
    if any(low.startswith(p) for p in _SHARED_PREFIXES):
        return SHARED
    if any(low.startswith(p) for p in _INFRA_PREFIXES):
        return INFRA
    return UNCLASSIFIED


# ─────────────────────────── sqlite acquisition ───────────────────────────


def export_sqlite(nsys_rep: Path, out_sqlite: Path, nsys_bin: str = "nsys") -> Path:
    """Export a .nsys-rep to SQLite via `nsys export`. Requires nsys on PATH."""
    if shutil.which(nsys_bin) is None:
        raise RuntimeError(
            f"'{nsys_bin}' not found on PATH; run inside the build container "
            f"(which has Nsight Systems), or pass an already-exported .sqlite.")
    subprocess.run([nsys_bin, "export", "--type", "sqlite",
                    "--force-overwrite", "true", "--output", str(out_sqlite),
                    str(nsys_rep)], check=True, stdout=subprocess.DEVNULL)
    return out_sqlite


def ensure_sqlite(path: Path, nsys_bin: str = "nsys",
                  keep: bool = False) -> tuple[Path, bool]:
    """Return (sqlite_path, is_temp). Exports if given a .nsys-rep."""
    if path.suffix.lower() == ".sqlite":
        return path, False
    if path.suffix.lower() == ".nsys-rep":
        out = path.with_suffix(".sqlite")
        export_sqlite(path, out, nsys_bin=nsys_bin)
        return out, not keep
    raise ValueError(f"unrecognized input (want .nsys-rep or .sqlite): {path}")


# ─────────────────────────── kernel loading ───────────────────────────


def load_kernels(sqlite_path: Path) -> list[dict]:
    """Load every kernel instance: name, duration, channel, CUDA context ids."""
    db = sqlite3.connect(str(sqlite_path))
    try:
        try:
            rows = db.execute(
                """
                SELECT s.value AS short_name, d.value AS demangled, k.start,
                       k.end, k.contextId, k.greenContextId
                FROM CUPTI_ACTIVITY_KIND_KERNEL k
                JOIN StringIds s ON s.id = k.shortName
                LEFT JOIN StringIds d ON d.id = k.demangledName
                ORDER BY k.start
                """
            ).fetchall()
        except sqlite3.OperationalError:
            # older nsys sqlite schema without demangledName
            rows = [(short, None, start, end, ctx, green)
                    for (short, start, end, ctx, green) in db.execute(
                        """
                        SELECT s.value AS short_name, k.start, k.end,
                               k.contextId, k.greenContextId
                        FROM CUPTI_ACTIVITY_KIND_KERNEL k
                        JOIN StringIds s ON s.id = k.shortName
                        ORDER BY k.start
                        """).fetchall()]
    finally:
        db.close()
    out = []
    for (short, demangled, start, end, ctx, green) in rows:
        out.append({
            "short_name":  short,
            "channel":     classify(short, demangled),
            "start_ns":    int(start),
            "dur_us":      (int(end) - int(start)) / 1000.0,
            "ctx":         ctx,
            "green_ctx":   green or 0,
        })
    return out


def detect_context_key(kernels: list[dict]) -> tuple[str, bool]:
    """Pick the grouping field: greenContextId if any non-zero, else contextId."""
    if any((k["green_ctx"] or 0) != 0 for k in kernels):
        return "green_ctx", True
    return "ctx", False


# ─────────────────────────── stats helpers ───────────────────────────


def _pct(sorted_vals: list[float], p: float) -> float:
    if not sorted_vals:
        return 0.0
    if len(sorted_vals) == 1:
        return sorted_vals[0]
    k = (len(sorted_vals) - 1) * (p / 100.0)
    lo, hi = math.floor(k), math.ceil(k)
    if lo == hi:
        return sorted_vals[int(k)]
    return sorted_vals[lo] * (hi - k) + sorted_vals[hi] * (k - lo)


def _latency_stats(durations_us: list[float]) -> dict:
    s = sorted(durations_us)
    n = len(s)
    return {
        "count":   n,
        "sum_us":  round(sum(s), 3),
        "mean_us": round(sum(s) / n, 3),
        "min_us":  round(s[0], 3),
        "max_us":  round(s[-1], 3),
        "p50_us":  round(_pct(s, 50), 3),
        "p90_us":  round(_pct(s, 90), 3),
        "p99_us":  round(_pct(s, 99), 3),
    }


# ─────────────────────────── report ───────────────────────────


def _dominant_channel(signal_kernels: list[dict]) -> str:
    """Context label: the channel with the most channel-specific busy time.

    Co-residency rule: PDCCH and CSI-RS share one context by design (CSI-RS
    runs inside the PDCCH CUDA context), and the dashboard expects that context
    to be the PDCCH report with the CSI-RS kernels shown within it. Busy time
    alone can flip the label whenever one of the two is optimized (e.g. the
    fused PDCCH kernel is faster than the CSI-RS pair), so when both are
    present PDCCH wins explicitly.
    """
    busy: dict = defaultdict(float)
    for k in signal_kernels:
        if k["channel"] not in (SHARED, INFRA, UNCLASSIFIED):
            busy[k["channel"]] += k["dur_us"]
    if not busy:
        return SHARED
    if "PDCCH" in busy and "CSI-RS" in busy:
        return "PDCCH"
    return max(busy, key=busy.get)


# ─────────────────────────── module detection ───────────────────────────
# A "module" is a functional group of kernels inferred from the *launch
# timeline* (not just kernel names), so a module can have several types that a
# name-only aggregate cannot tell apart. The type is the number of DMRS symbols
# in a channel-estimation pass.
#
# PUSCH (the only channel with modules defined today). The receiver runs a
# repeating cycle per channel-estimation pass-batch:
#     windowedChEstPre ... chEstFilter ... eqMmseCoefComp ... eqMmseSoftDemap
# but the launches are NOT always one-pass-at-a-time. A batch may launch several
# windowedChEstPre back-to-back and then their chEstFilter kernels (e.g. 4
# windowed then 4 filters), or interleave them. So we cannot simply split at each
# windowed (that miscounts N). Instead we group a batch as: all windowed (+ their
# filters) up to the point equalization (eqCoef/eqDemap) begins; the next
# windowed seen *after* equalization starts a new batch (a large launch-time gap
# also starts a new batch, as a safety). Within a batch with W windowed and F
# filters, the DMRS-symbol count per pass is N = round(F / W), and the batch
# contributes W passes of type N. The MMSE-filtering and channel-equalization
# modules inherit N/W from the channel-estimation batch (their own kernels are
# harder to segment, so we use the DMRS number derived from channel estimation).
# Per pass (mean within a batch is sum-over-batch / W):
#   (1) channel_estimation   = windowedChEstPre + N x chEstFilter
#   (2) mmse_filtering        = N x chEstFilter            (overlaps (1) by design)
#   (3) channel_equalization  = N x eqMmseCoefComp + eqMmseSoftDemap

_PUSCH_WINDOWED = "windowedchestprenodftsofdmkernel"
_PUSCH_FILTER = "chestfilternodftsofdmdispatchkernel"
_PUSCH_EQ_COEF_PREFIX = "eqmmsecoefcomp"
_PUSCH_EQ_DEMAP_PREFIX = "eqmmsesoftdemap"

# A windowedChEstPre this long (ns) after the previous module kernel starts a new
# batch even if equalization hasn't been seen yet — guards against two passes
# with no in-context equalization merging. Batches in practice are <~65us wide;
# slot boundaries are >~85us, so the threshold sits comfortably between.
_PUSCH_BATCH_GAP_NS = 200_000.0


def _detect_pusch_modules(ordered: list[dict]) -> list[dict]:
    """Group PUSCH kernels (in launch order) into per-DMRS-symbol modules."""
    batches: list[dict] = []
    cur = None
    last_start = None
    for k in ordered:
        n = _norm(k["short_name"])
        is_w = n == _PUSCH_WINDOWED
        is_f = n == _PUSCH_FILTER
        is_c = n.startswith(_PUSCH_EQ_COEF_PREFIX)
        is_d = n.startswith(_PUSCH_EQ_DEMAP_PREFIX)
        if not (is_w or is_f or is_c or is_d):
            continue
        start = k.get("start_ns")
        if is_w:
            far = (last_start is not None and start is not None
                   and start - last_start > _PUSCH_BATCH_GAP_NS)
            if cur is None or cur["eq"] or far:
                cur = {"windowed": [], "filter": [], "coef": [], "demap": [],
                       "eq": False}
                batches.append(cur)
            cur["windowed"].append(k["dur_us"])
        elif cur is not None:
            if is_f:
                cur["filter"].append(k["dur_us"])
            elif is_c:
                cur["coef"].append(k["dur_us"])
                cur["eq"] = True
            elif is_d:
                cur["demap"].append(k["dur_us"])
                cur["eq"] = True
        if start is not None:
            last_start = start

    # Aggregate batches by N = round(filters / windowed), the per-pass DMRS count.
    # Each batch contributes W passes; module mean = total batch time / W.
    by_type: dict = defaultdict(lambda: defaultdict(lambda: {"sum": 0.0, "count": 0}))
    for b in batches:
        w = len(b["windowed"])
        f = len(b["filter"])
        if w == 0 or f == 0:
            continue
        n_dmrs = max(1, round(f / w))
        for module, total in (
            ("channel_estimation", sum(b["windowed"]) + sum(b["filter"])),
            ("mmse_filtering", sum(b["filter"])),
            ("channel_equalization", sum(b["coef"]) + sum(b["demap"])),
        ):
            agg = by_type[n_dmrs][module]
            agg["sum"] += total
            agg["count"] += w

    out: list[dict] = []
    for n_dmrs in sorted(by_type):
        for module in ("channel_estimation", "mmse_filtering",
                       "channel_equalization"):
            agg = by_type[n_dmrs].get(module)
            if not agg or agg["count"] == 0:
                continue
            out.append({
                "module": module,
                "dmrs_symbols": n_dmrs,
                "segment_count": agg["count"],
                "sum_us": round(agg["sum"], 3),
                "mean_us": round(agg["sum"] / agg["count"], 3),
            })
    return out


def detect_modules(channel: str, ordered_signal: list[dict]) -> list[dict]:
    """Per-channel module breakdown from the ordered (launch-time) kernel list.

    Only PUSCH has modules defined today; other channels return []. ``modules``
    is therefore purely additive — channels/dashboards that don't use it ignore it.
    """
    if channel == "PUSCH":
        return _detect_pusch_modules(ordered_signal)
    return []


def build_report(kernels: list[dict], *, source: str) -> dict:
    key_field, is_green = detect_context_key(kernels)

    unknown = sorted({k["short_name"] for k in kernels
                      if k["channel"] == UNCLASSIFIED})
    if unknown:
        print(f"[nsys_parser] WARNING: {len(unknown)} unclassified kernel "
              f"name(s) kept as {UNCLASSIFIED} — extend _CHANNEL_KERNELS or "
              f"_NAMESPACE2CHANNEL: {', '.join(unknown)}", file=sys.stderr)

    by_ctx: dict = defaultdict(list)
    for k in kernels:
        by_ctx[k[key_field]].append(k)

    channels = []
    dropped = []
    for ctx_id, klist in by_ctx.items():
        signal = [k for k in klist if k["channel"] != INFRA]
        if not signal:
            dropped.append({"context_id": ctx_id, "reason": "timing/infra-only",
                            "kernel_count": len(klist)})
            continue

        by_name: dict = defaultdict(list)
        for k in signal:
            by_name[k["short_name"]].append(k)
        kernel_entries = []
        for name in sorted(by_name, key=lambda n: -sum(x["dur_us"]
                                                       for x in by_name[n])):
            insts = by_name[name]
            durs = [x["dur_us"] for x in insts]
            kernel_entries.append({
                "kernel":        name,
                "kernel_channel": insts[0]["channel"],   # channel / (shared)
                "latency":       _latency_stats(durs),    # aggregated
                "instances_us":  [round(d, 3) for d in durs],  # separate
            })

        ch_label = _dominant_channel(signal)
        channels.append({
            "channel":        ch_label,
            "context_id":     ctx_id,
            "kernel_count":   len(signal),
            "kernel_busy_us": round(sum(k["dur_us"] for k in signal), 3),
            "kernels":        kernel_entries,
            "modules":        detect_modules(ch_label, signal),
        })

    channels.sort(key=lambda c: -c["kernel_busy_us"])
    return {
        "source":           source,
        "context_type":     "green" if is_green else "mps",
        "num_channels":     len(channels),
        "channels":         channels,
        "dropped_contexts": dropped,
    }


def parse_nsys(path, nsys_bin: str = "nsys") -> dict:
    """Library entry point: parse a .nsys-rep or .sqlite into the report dict.

    Exports a .nsys-rep to a temporary sqlite (requires ``nsys``) and cleans it
    up afterwards. Raises on failure so the caller can decide whether to
    soft-fail (the Aerial GPU Benchmark extractor treats nsys as optional).
    """
    p = Path(path)
    sqlite_path, is_temp = ensure_sqlite(p, nsys_bin=nsys_bin)
    try:
        return build_report(load_kernels(sqlite_path), source=p.name)
    finally:
        if is_temp and sqlite_path.exists():
            try:
                sqlite_path.unlink()
            except OSError:
                pass


# ─────────────────────────── main ───────────────────────────


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Parse an Aerial GPU Benchmark nsys-rep/sqlite into per-channel "
                    "kernel latency (context + static cuPHY map; latency only).")
    ap.add_argument("input", help="A .nsys-rep (needs `nsys`) or a .sqlite.")
    ap.add_argument("-o", "--output", default=None,
                    help="Write JSON here (default: stdout).")
    ap.add_argument("--nsys-bin", default="nsys",
                    help="Path to the nsys binary (default: nsys on PATH).")
    ap.add_argument("--keep-sqlite", action="store_true",
                    help="Keep the exported .sqlite next to a .nsys-rep input.")
    args = ap.parse_args()

    src = Path(args.input)
    if not src.is_file():
        print(f"ERROR: input not found: {src}", file=sys.stderr)
        return 2

    try:
        sqlite_path, is_temp = ensure_sqlite(
            src, nsys_bin=args.nsys_bin, keep=args.keep_sqlite)
    except (RuntimeError, ValueError, subprocess.CalledProcessError) as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1

    try:
        kernels = load_kernels(sqlite_path)
        if not kernels:
            print("ERROR: no kernels found in trace", file=sys.stderr)
            return 1
        report = build_report(kernels, source=src.name)
    finally:
        if is_temp and sqlite_path.exists():
            try:
                sqlite_path.unlink()
            except OSError:
                pass

    text = json.dumps(report, indent=2)
    if args.output:
        Path(args.output).write_text(text + "\n")
        print(f"[nsys_parser] {report['context_type']} contexts -> "
              f"{report['num_channels']} channel reports -> {args.output}",
              file=sys.stderr)
        for ch in report["channels"]:
            print(f"  {ch['channel']:8s} ctx={ch['context_id']:<4} "
                  f"{ch['kernel_count']:4d} kernels  "
                  f"{ch['kernel_busy_us']:9.1f}us busy  "
                  f"({len(ch['kernels'])} distinct)", file=sys.stderr)
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
