# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Memory Performance Plotting Script

This script generates memory usage and frequency plots from GPU performance measurement data. The input json file can be generated by running the testbench using Python interface with --measure_power option.

Expected Input File Format:
- JSON files containing GPU performance data from nvidia-smi measurements
- Each file should have the following structure:
  {
    "testConfig": {
      ...,
      "sweeps": number_of_sweeps,
      ...,
      "gpuName": "GPU Model Name",
      ...,
    },
    "XX": [  // where XX is the cell count (e.g., "08+00", "12+00", etc.)
      [sm_clock, mem_clock, power_draw, mem_used, gpu_util, mem_util, temperature],
      [sm_clock, mem_clock, power_draw, mem_used, gpu_util, mem_util, temperature],
      ...
    ]
  }

Example JSON structure:
  {
    "testConfig": {
      ...,
      "sweeps": 8,
      ...,
      "gpuName": "NVIDIA GH200 480GB",
      ...,
    },
    "08+00": [
      [1980, 2619, 143.28, 8192, 95, 4, 31],
      [1875, 2619, 145.12, 8256, 92, 4, 32]
    ]
  }

Usage:
  python memory_plot.py --filenames file1.json --cells 8+0

Output:
- Generates memory.png with two subplots:
  1. CDF of memory frequency distribution
  2. Memory usage over time
"""

import json
import matplotlib.pyplot as plt
import argparse
import numpy as np
import os

from util import to_float, to_int, well_formed_samples

base = argparse.ArgumentParser()
base.add_argument(
    "--filenames",
    type=str,
    nargs="+",
    dest="filenames",
    help="Specifies the files containing the results",
    required=True,
)
base.add_argument(
    "--cells",
    type=str,
    dest="cells",
    help="Specifies the number of cells to focus analysis on",
    required=True,
)
base.add_argument(
    "--short_legend",
    action="store_true",
    default=False,
    dest="is_short_legend",
    help="whether add platform and nSlots in each legend",
)
args = base.parse_args()

gpu_freq = []
mem_freq = []
mem_used = []
testConfig = []

if "+" in args.cells:
    cells = "+".join([str(x).zfill(2) for x in args.cells.split("+")])
else:
    cells = str(args.cells).zfill(2)

for filename in args.filenames:
    try:
        with open(filename, "r") as ifile:
            try:
                data = json.load(ifile)
            except json.JSONDecodeError as e:
                print(f"Error parsing JSON from {filename}: {e}")
                continue

            samples = data.get(cells)
            if samples is None:
                print(f"  [{filename}] missing cell key '{cells}', skipping")
                continue

            well_formed, skipped = well_formed_samples(samples, min_fields=4)
            if skipped:
                print(f"  [{filename}] {skipped} malformed sample row(s) skipped (need >=4 fields)")

            raw_gpu_freq = [to_int(x[0]) for x in well_formed]
            raw_mem_freq = [to_int(x[1]) for x in well_formed]
            na_gpu = sum(1 for v in raw_gpu_freq if v is None)
            na_mem = sum(1 for v in raw_mem_freq if v is None)
            if na_gpu:
                print(f"  [{filename}] {na_gpu} GPU freq sample(s) reported N/A")
            if na_mem:
                print(f"  [{filename}] {na_mem} mem freq sample(s) reported N/A")

            gpu_freq.extend([v for v in raw_gpu_freq if v is not None])
            mem_freq.extend([v for v in raw_mem_freq if v is not None])
            mem_used.extend([to_float(x[3]) for x in well_formed])

            # Add test config once per file, not for each data point
            testConfig.append(data['testConfig']['gpuName'] + ' ' + str(data['testConfig']['sweeps']) + ' slots')

    except IOError as e:
        print(f"Error opening file {filename}: {e}")
        continue

valid_mem_used = [v for v in mem_used if not np.isnan(v)]
max_mem_used = np.max(valid_mem_used) if valid_mem_used else None
std_mem_freq = np.std(mem_freq) if mem_freq else None

if max_mem_used is not None or std_mem_freq is not None:
    parts = []
    parts.append(f"Maximum memory used: {max_mem_used} MiB" if max_mem_used is not None else "Maximum memory used: N/A")
    parts.append(f"Memory frequency std.: {std_mem_freq}" if std_mem_freq is not None else "Memory frequency std.: N/A")
    print(", ".join(parts))

if mem_freq or valid_mem_used:
    plt.subplots(1, 2, figsize=(2 * 7.2, 4.8))
    plt.subplot(1, 2, 1)
    if mem_freq:
        y, x = np.histogram(mem_freq, bins=1000)
        cy = np.cumsum(y) / len(mem_freq)
        plt.plot(x[1:], cy)
        folder, _ = os.path.split(args.filenames[0])
        if folder.split("/")[-1].isnumeric():
            plt.legend(["Mem. Freq. capped at " + folder.split("/")[-1] + " MHz"])
    else:
        plt.text(0.5, 0.5, "N/A", ha="center", va="center", transform=plt.gca().transAxes)
    plt.grid(True)
    plt.xlabel("Memory Frequency Cont. Load [MHz]")
    plt.ylabel("CDF")

    plt.subplot(1, 2, 2)
    plt.grid(True)
    valid_mem_points = [(i, v) for i, v in enumerate(mem_used) if not np.isnan(v)]
    if valid_mem_points:
        idx = [i for i, _ in valid_mem_points]
        vals = [v for _, v in valid_mem_points]
        plt.plot(np.array(idx) * 1e-3, vals)
    else:
        plt.text(0.5, 0.5, "N/A", ha="center", va="center", transform=plt.gca().transAxes)
    plt.xlabel("Time [s]")
    plt.ylabel("Memory Used [MiB]")

    if not args.is_short_legend:
        plt.legend(testConfig)

    plt.savefig("memory.png")
    # plt.show()
