#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""KS-statistic gate for the gpu3gppchan calibration test.

The calibration analysis (util/analysis_channel_stats.py, invoked with
`--log-level INFO --log-file <leg>/analysis.log`) logs one line per metric:

    <ts> - INFO - <metric name> KS statistic: 0.0421, p-value: 0.9876

This tool has two modes:

  --derive   Scan <results>/<leg>/analysis.log for every leg, record the
             observed KS statistic per metric, and write a thresholds YAML
             with threshold = min(1.0,
             max(observed * (1 + margin), observed + 0.02)).
             Run this once against a known-good baseline at the CICD seed
             counts (UMa 5 seeds, ISAC 50 seeds).

  (default)  Gate mode: re-parse the logs of a fresh run and FAIL (exit 1) if
             any metric's KS statistic exceeds its threshold, or if a metric
             recorded in the thresholds file is missing from the run.
             Metrics present in the run but absent from the thresholds file
             produce a warning only (re-derive to include them).
"""

import argparse
import re
import sys
from pathlib import Path

import yaml

KS_LINE = re.compile(
    r"- INFO - (?P<metric>.+?) KS statistic: (?P<ks>[0-9.]+), p-value: (?P<pval>[0-9.eE+-]+)"
)


def parse_leg_logs(results_dir: Path) -> dict:
    """Return {leg_name: {metric: max_ks}} from <results>/<leg>/analysis.log."""
    legs = {}
    for log in sorted(results_dir.glob("*/analysis.log")):
        leg = log.parent.name
        metrics = {}
        for line in log.read_text(errors="replace").splitlines():
            m = KS_LINE.search(line)
            if m:
                ks = float(m.group("ks"))
                metric = m.group("metric").strip()
                # keep the worst (largest) KS if a metric is logged twice
                metrics[metric] = max(ks, metrics.get(metric, 0.0))
        if metrics:
            legs[leg] = metrics
        else:
            print(f"WARNING: no KS statistics found in {log}", file=sys.stderr)
    return legs


def derive(legs: dict, thresholds_path: Path, margin: float) -> int:
    if not legs:
        print("ERROR: no analysis logs with KS statistics found — nothing to derive",
              file=sys.stderr)
        return 1
    out = {"margin": margin, "legs": {}}
    for leg, metrics in sorted(legs.items()):
        out["legs"][leg] = {}
        for metric, ks in sorted(metrics.items()):
            threshold = min(1.0, max(ks * (1.0 + margin), ks + 0.02))
            out["legs"][leg][metric] = {
                "observed": round(ks, 4),
                "threshold": round(threshold, 4),
            }
    header = (
        "# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.\n"
        "# SPDX-License-Identifier: Apache-2.0\n"
        "#\n"
        "# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
        "# you may not use this file except in compliance with the License.\n"
        "# You may obtain a copy of the License at\n"
        "#\n"
        "# http://www.apache.org/licenses/LICENSE-2.0\n"
        "#\n"
        "# Unless required by applicable law or agreed to in writing, software\n"
        "# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
        "# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
        "# See the License for the specific language governing permissions and\n"
        "# limitations under the License.\n"
        "\n"
        "# Auto-generated by check_ks_gate.py --derive from a known-good baseline\n"
        "# run at the CICD seed counts (UMa seeds 0-4, ISAC seeds 0-49).\n"
        "# threshold = min(1.0, max(observed * (1 + margin), observed + 0.02))\n"
        "# Regenerate after intentional model changes; see test/README.md.\n"
    )
    thresholds_path.write_text(header + yaml.safe_dump(out, sort_keys=False))
    n = sum(len(m) for m in legs.values())
    print(f"Wrote {n} thresholds for {len(legs)} legs to {thresholds_path}")
    return 0


def gate(legs: dict, thresholds_path: Path) -> int:
    if not thresholds_path.is_file():
        print(f"ERROR: thresholds file not found: {thresholds_path}\n"
              f"Run with --derive against a known-good baseline first.", file=sys.stderr)
        return 1
    ref = yaml.safe_load(thresholds_path.read_text()) or {}
    ref_legs = ref.get("legs") or {}
    if not ref_legs:
        print(f"ERROR: no thresholds defined in {thresholds_path}", file=sys.stderr)
        return 1

    failures, warnings, checked = [], [], 0
    for leg, metrics in sorted(ref_legs.items()):
        run_metrics = legs.get(leg)
        if run_metrics is None:
            failures.append(f"[{leg}] no analysis.log with KS statistics in this run")
            continue
        for metric, entry in sorted(metrics.items()):
            threshold = float(entry["threshold"])
            ks = run_metrics.get(metric)
            if ks is None:
                failures.append(f"[{leg}] metric '{metric}' missing from run")
                continue
            checked += 1
            verdict = "PASS" if ks <= threshold else "FAIL"
            print(f"  {verdict}  [{leg}] {metric}: KS={ks:.4f} (threshold {threshold:.4f})")
            if ks > threshold:
                failures.append(
                    f"[{leg}] {metric}: KS={ks:.4f} > threshold {threshold:.4f}")
        for metric in sorted(set(run_metrics) - set(metrics)):
            warnings.append(f"[{leg}] new metric '{metric}' not in thresholds file "
                            f"(KS={run_metrics[metric]:.4f}) — consider re-deriving")
    for leg in sorted(set(legs) - set(ref_legs)):
        warnings.append(f"leg '{leg}' not in thresholds file — consider re-deriving")

    print(f"\nKS gate: {checked} metrics checked, "
          f"{len(failures)} failure(s), {len(warnings)} warning(s)")
    for w in warnings:
        print(f"  WARNING: {w}")
    for f in failures:
        print(f"  FAILURE: {f}")
    return 1 if failures else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results", required=True,
                        help="Calibration results root (contains <leg>/analysis.log)")
    parser.add_argument("--thresholds", required=True, help="Path to ks_thresholds.yaml")
    parser.add_argument("--derive", action="store_true",
                        help="Derive thresholds from this run instead of gating")
    parser.add_argument("--margin", type=float, default=0.5,
                        help="Relative headroom used by --derive (default: 0.5)")
    args = parser.parse_args()

    legs = parse_leg_logs(Path(args.results))
    if args.derive:
        return derive(legs, Path(args.thresholds), args.margin)
    return gate(legs, Path(args.thresholds))


if __name__ == "__main__":
    sys.exit(main())
