#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Run Aerial GPU Benchmark CICD cases from cicd_cases.json."""

from __future__ import annotations

import argparse
import json
import os
import re
import platform
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml


SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_DB = SCRIPT_DIR / "cicd_cases.json"
GENERATED_DIR = SCRIPT_DIR / ".generated"
CUMAC_ONNX_CASE_PREFIX = "8002"


def _rewrite_yaml_for_arch(source_yaml: Path) -> tuple[Path, str]:
    """Return (resolved path, SCRIPT_DIR-relative string) for the active YAML.

    On x86_64 hosts, copies the YAML to GENERATED_DIR with ``build.aarch64``
    replaced by ``build.x86_64``.  On other architectures the source is
    returned unchanged.
    """
    try:
        rel = str(source_yaml.relative_to(SCRIPT_DIR))
    except ValueError:
        rel = str(source_yaml)

    if platform.machine() != "x86_64":
        return source_yaml, rel

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    dest = GENERATED_DIR / source_yaml.name
    text = source_yaml.read_text(encoding="utf-8")
    dest.write_text(text.replace("build.aarch64", "build.x86_64"), encoding="utf-8")
    return dest, str(dest.relative_to(SCRIPT_DIR))


def find_project_root(start: Path) -> Path:
    """Find the SDK root containing the perf measurement script.

    Args:
        start (Path): Path where the upward SDK-root search begins.

    Returns:
        Path: SDK root that contains ``testBenches/perf/measure.py``.

    Raises:
        RuntimeError: If no SDK root can be found.

    Examples:
        >>> root = find_project_root(SCRIPT_DIR)
    """
    for candidate in (start, *start.parents):
        if (candidate / "testBenches" / "perf" / "measure.py").is_file():
            return candidate
    raise RuntimeError(f"Could not locate SDK root from {start}")


PROJECT_ROOT = find_project_root(SCRIPT_DIR)

OFFLINE_SCRIPT_TEMPLATE = r'''#!/usr/bin/env bash
# Auto-generated by run_cicd_cases.py.
# Case @@CASE_ID@@: @@LONG_NAME@@

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
SDK_ROOT="${cuBB_SDK:-}"
if [[ -z "$SDK_ROOT" ]]; then
  search_dir="$SCRIPT_DIR"
  while [[ "$search_dir" != "/" ]]; do
    if [[ -f "$search_dir/testBenches/perf/measure.py" ]]; then
      SDK_ROOT="$search_dir"
      break
    fi
    search_dir=$(dirname "$search_dir")
  done
fi
if [[ -z "$SDK_ROOT" || ! -f "$SDK_ROOT/testBenches/perf/measure.py" ]]; then
  echo "ERROR: Could not locate SDK root. Set cuBB_SDK or run from the SDK checkout." >&2
  exit 1
fi
PERF_DIR="$SDK_ROOT/testBenches/perf"
export cuBB_SDK="$SDK_ROOT"

# ---- Case configuration ----
case_id="@@CASE_ID@@"
case_name="@@LONG_NAME@@"
case_delta="@@DELTA@@"
yaml_file="$SCRIPT_DIR/@@YAML_FILE@@"
usecase="@@USECASE@@"
supported_gpus="@@SUPPORTED_GPUS@@"
enable_cumac="@@ENABLE_CUMAC@@"
enable_cumac_airan="@@ENABLE_CUMAC_AIRAN@@"

smAllocation=""
gpu_freq=""
gpu_power=""
expected_capacity=""
config_source=""
matched_gpu_tag=""
gc_sm_alloc=""
enlarge_cuphy_h_limits=""

# ---- Workflow knobs ----
function_slots="@@FUNCTION_SLOTS@@"
function_cells="@@FUNCTION_CELLS@@"
confirm_slots="@@CONFIRM_SLOTS@@"
power_start="@@POWER_START@@"
power_slots="@@POWER_SLOTS@@"
power_iterations="@@POWER_ITERATIONS@@"
nsys_slots="@@NSYS_SLOTS@@"
nsys_delay="@@NSYS_DELAY@@"
nsys_iterations="@@NSYS_ITERATIONS@@"

dry_run=0
do_build=0
output_root="$SCRIPT_DIR/runs"
run_id="$(date +%Y%m%d_%H%M%S)"

usage() {
  cat <<USAGE
Usage: $(basename "$0") [--dry-run] [--build] [--slots N] [--output-root DIR] [--run-id NAME]

Runs CICD case $case_id ($case_name):
  1. 2C functionality ref_check
  2. confirm_cell_capacity.py starting at expected capacity
  3. power sweep from 1C through confirmed capacity
  4. nsys trace for each latency-confirmation swept cell

Options:
  --slots N          Override confirm_cell_capacity.py slots
USAGE
}

require_value() {
  local option="$1"
  if [[ $# -lt 2 || -z "${2:-}" || "${2:-}" == --* ]]; then
    echo "ERROR: $option requires a value" >&2
    exit 2
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run)
      dry_run=1
      shift
      ;;
    --build)
      do_build=1
      shift
      ;;
    --slots)
      require_value "$@"
      confirm_slots="$2"
      shift 2
      ;;
    --output-root)
      require_value "$@"
      output_root="$2"
      shift 2
      ;;
    --run-id)
      require_value "$@"
      run_id="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

RUN_DIR="$output_root/$case_id/$run_id"

# set -euo pipefail aborts on the first failing command; several steps capture
# their output into variables (visible only in $RUN_DIR/*.log), so without this
# trap the wrapper can die with nothing on the console.
trap 'rc=$?; echo "ERROR: wrapper aborted (exit $rc) at line $LINENO: $BASH_COMMAND" >&2; echo "       check the step logs under ${RUN_DIR:-<run dir not created yet>}/" >&2' ERR

detected_gpu=""
if command -v nvidia-smi >/dev/null 2>&1; then
  detected_gpu=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1 | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' || true)
fi
case "$detected_gpu" in
  *"failed because it couldn't communicate"*) detected_gpu="" ;;
esac
detected_gpu_tag=""
case "$detected_gpu" in
  *GH200*|*"H200"*) detected_gpu_tag="GH200" ;;
  *"RTX PRO 4500"*|*GB203*) detected_gpu_tag="RTX_PRO_4500" ;;
  "") detected_gpu_tag="UNKNOWN" ;;
  *) detected_gpu_tag="OTHER" ;;
esac
# Manual override for testing without driver (e.g. AERIAL_GPU_TAG=GH200 bash cubb_gpu_test_80001.sh --dry-run)
if [[ -n "${AERIAL_GPU_TAG:-}" ]]; then
  detected_gpu_tag="$AERIAL_GPU_TAG"
  detected_gpu="${detected_gpu:-(override AERIAL_GPU_TAG=$AERIAL_GPU_TAG)}"
fi

# Per-GPU config selection (generated from cicd_cases.json gpu_configs)
fallback_gpu="@@FALLBACK_GPU@@"
case "$detected_gpu_tag" in
@@GPU_CONFIG_CASES@@
  *)
@@FALLBACK_BRANCH@@
    ;;
esac

# measure.py appends "_gc" to its output prefix when the case YAML enables
# green contexts; the generator bakes the matching suffix in here.
fileNameStr=$(printf '%03d_' $smAllocation | sed 's/_$//')@@GC_SUFFIX@@
sweep_json="${fileNameStr}_sweep_graphs_avg_${usecase}.json"
power_json="${fileNameStr}_power_graphs_avg_${usecase}.json"

log() {
  echo "[$(date +%H:%M:%S)] $*"
}

banner() {
  echo
  echo "=============================================================================="
  echo "  $*"
  echo "=============================================================================="
}

run_cmd() {
  log "$*"
  if [[ "$dry_run" == "1" ]]; then
    return 0
  fi
  "$@"
}

run_logged() {
  local log_file="$1"
  shift
  log "$*"
  if [[ "$dry_run" == "1" ]]; then
    log "[dry-run] would write command output to $log_file"
    return 0
  fi
  "$@" 2>&1 | tee "$log_file"
}

find_confirm_script() {
  if [[ -f "$PERF_DIR/confirm_cell_capacity.py" ]]; then
    echo "$PERF_DIR/confirm_cell_capacity.py"
    return 0
  fi
  if [[ -f "$SDK_ROOT/aerial-gpu-benchmark/confirm_cell_capacity.py" ]]; then
    echo "$SDK_ROOT/aerial-gpu-benchmark/confirm_cell_capacity.py"
    return 0
  fi
  echo "ERROR: confirm_cell_capacity.py not found" >&2
  return 1
}

parse_cell_capacity() {
  local output="$1"
  local cap
  cap=$(echo "$output" | grep -oP 'Cell capacity\s*=\s*\K\d+' | tail -1 || true)
  if [[ -z "$cap" ]]; then
    cap=$(echo "$output" | grep -oP 'Cell capacity is \K\d+' | tail -1 || true)
  fi
  if [[ -z "$cap" ]]; then
    cap=$(echo "$output" | grep -oP 'Confirmed capacity:\s*\K\d+' | tail -1 || true)
  fi
  if [[ -z "$cap" ]]; then
    echo "ERROR: Could not parse confirmed cell capacity from confirm_cell_capacity.py output." >&2
    echo "ERROR: Expected one of: 'Cell capacity = <N>', 'Cell capacity is <N>', or 'Confirmed capacity: <N>'." >&2
    if [[ -n "$output" ]]; then
      echo "ERROR: confirm_cell_capacity.py output:" >&2
      echo "$output" >&2
    fi
    exit 1
  fi
  echo "$cap"
}

json_cells_or_default() {
  local json_file="$1"
  local fallback="$2"
  if [[ ! -f "$json_file" ]]; then
    echo "$fallback"
    return 0
  fi
  python3 - "$json_file" "$fallback" <<'PY'
import json
import re
import sys
from pathlib import Path

path = Path(sys.argv[1])
fallback = sys.argv[2]
try:
    data = json.loads(path.read_text())
except (OSError, json.JSONDecodeError):
    print(fallback)
    raise SystemExit(0)

cells = []
for key in data:
    if key == "testConfig":
        continue
    m = re.match(r"(\d+)\+", str(key))
    if m:
        cells.append(int(m.group(1)))
print(" ".join(str(x) for x in sorted(set(cells))) or fallback)
PY
}

cell_keys() {
  local out=()
  local cell
  for cell in "$@"; do
    out+=("${cell}+0")
  done
  printf '%s\n' "${out[@]}"
}

copy_if_exists() {
  local src="$1"
  local dst="$2"
  if [[ "$dry_run" == "1" ]]; then
    return 0
  fi
  if [[ -f "$src" ]]; then
    cp "$src" "$dst"
  fi
}

echo "Case              : $case_id"
echo "Name              : $case_name"
echo "Delta             : $case_delta"
echo "Detected GPU      : ${detected_gpu:-N/A} (tag: $detected_gpu_tag)"
echo "Supported GPUs    : $supported_gpus"
echo "Enable cuMAC      : $enable_cumac"
echo "Enable cuMAC AIRAN: $enable_cumac_airan"
echo "YAML              : $yaml_file"
echo "SM allocation     : $smAllocation"
echo "GC SM ranges      : ${gc_sm_alloc:-none}"
echo "Enlarge cuPHY.h limits: ${enlarge_cuphy_h_limits}"
echo "Freq / power      : ${gpu_freq} MHz / ${gpu_power} W"
echo "Expected capacity : ${expected_capacity}C"
echo "Output            : $RUN_DIR"

if [[ "$dry_run" == "1" ]]; then
  log "[dry-run] mkdir -p $RUN_DIR/nsys"
  log "[dry-run] cp $yaml_file $RUN_DIR/"
else
  mkdir -p "$RUN_DIR/nsys"
  cp "$yaml_file" "$RUN_DIR/"
fi

# ---- Green-context SM split ranges (cicd_cases.json green_context_sm_alloc) ----
# The testbench reads green-context split ranges ([split_start, sm_count] per
# channel) only from its YAML -- they cannot be passed through measure.py CLI
# args. When the matched gpu_configs entry carries green_context_sm_alloc,
# materialize a temp YAML with the ranges appended at the root and point the
# rest of the run at it. A root-level block overrides any config-level
# green_context_sm_alloc default embedded in the case YAML.
if [[ -n "$gc_sm_alloc" ]]; then
  gc_yaml_name="$(basename "$yaml_file" .yaml)_gc_${matched_gpu_tag}.yaml"
  gc_yaml="$RUN_DIR/$gc_yaml_name"
  if [[ "$dry_run" == "1" ]]; then
    log "[dry-run] would write green-context temp yaml $gc_yaml with ranges: $gc_sm_alloc"
    log "[dry-run] subsequent steps would use --yaml $gc_yaml"
    yaml_file="$gc_yaml"
  else
    GC_SM_ALLOC="$gc_sm_alloc" python3 - "$yaml_file" "$gc_yaml" <<'PYEOF'
import json
import os
import sys

src, dst = sys.argv[1], sys.argv[2]
alloc = json.loads(os.environ["GC_SM_ALLOC"])
lines = [
    "",
    "# Green-context SM split ranges injected by the CICD wrapper for the",
    "# detected GPU; [split_start, sm_count] per channel. This root-level block",
    "# overrides any config-level green_context_sm_alloc in the case YAML.",
    "green_context_sm_alloc:",
]
for ch, v in alloc.items():
    lines += [f"  {ch}:", f"  - {int(v[0])}", f"  - {int(v[1])}"]
with open(src, "r", encoding="utf-8") as f:
    text = f.read()
with open(dst, "w", encoding="utf-8") as f:
    f.write(text.rstrip("\n") + "\n" + "\n".join(lines) + "\n")
PYEOF
    yaml_file="$gc_yaml"
    log "green-context temp yaml: $yaml_file"
  fi
fi

build_dir="$SDK_ROOT/build.$(uname -m)"
cmake_cache="$build_dir/CMakeCache.txt"
limits_variant="standard"
if [[ "$enlarge_cuphy_h_limits" == "ON" ]]; then
  limits_variant="enlarged"
fi
limits_variant_stamp="$build_dir/.cicd_cuphy_h_limits_variant"
built_limits_variant=""
if [[ -f "$limits_variant_stamp" ]]; then
  built_limits_variant="$(<"$limits_variant_stamp")"
fi
profile_rebuild=0
cached_enable_cumac="OFF"
if grep -Eq '^ENABLE_CUMAC:BOOL=(ON|TRUE|YES|1)$' "$cmake_cache" 2>/dev/null; then
  cached_enable_cumac="ON"
fi
if [[ "$enable_cumac" != "$cached_enable_cumac" ]]; then
  log "ENABLE_CUMAC is $cached_enable_cumac in $cmake_cache but $enable_cumac is required; rebuilding"
  profile_rebuild=1
fi
cached_enable_cumac_airan="OFF"
if grep -Eq '^ENABLE_CUMAC_AIRAN:BOOL=(ON|TRUE|YES|1)$' "$cmake_cache" 2>/dev/null; then
  cached_enable_cumac_airan="ON"
fi
if [[ "$enable_cumac_airan" != "$cached_enable_cumac_airan" ]]; then
  log "ENABLE_CUMAC_AIRAN is $cached_enable_cumac_airan in $cmake_cache but $enable_cumac_airan is required; rebuilding"
  profile_rebuild=1
fi

if [[ "$limits_variant" != "$built_limits_variant" ]]; then
  log "64C limit build variant is ${built_limits_variant:-unknown}; $limits_variant is required; rebuilding"
  profile_rebuild=1
fi

limits_header="$SDK_ROOT/cuPHY/src/cuphy/cuphy.h"
limits_header_backup=""
restore_enlarged_cuphy_h_limits() {
  if [[ -n "$limits_header_backup" && -f "$limits_header_backup" ]]; then
    cp --preserve=mode "$limits_header_backup" "$limits_header"
    rm -f "$limits_header_backup"
    log "Restored standard cuPHY 64C limits in $limits_header"
  fi
}
trap restore_enlarged_cuphy_h_limits EXIT

apply_enlarged_cuphy_h_limits() {
  limits_header_backup="$(mktemp "${TMPDIR:-/tmp}/cuphy.h.cicd_cuphy_h_limits.XXXXXX")"
  cp --preserve=mode "$limits_header" "$limits_header_backup"
  python3 - "$limits_header" <<'PYEOF'
from pathlib import Path
import re
import sys

header = Path(sys.argv[1])
text = header.read_text(encoding="utf-8")
replacements = {
    "MAX_N_TBS_PER_CELL_GROUP_SUPPORTED": 512,
    "MAX_N_USER_GROUPS_SUPPORTED": 512,
    "MAX_CELLS_PER_SLOT": 64,
    "PDSCH_MAX_UES_PER_CELL_GROUP": 512,
    "PDSCH_MAX_UE_GROUPS_PER_CELL_GROUP": 512,
}
lines = text.splitlines(keepends=True)
counts = {name: 0 for name in replacements}
in_64c_branch = False
for index, line in enumerate(lines):
    stripped = line.strip()
    if stripped == "#ifdef ENABLE_64C":
        in_64c_branch = True
    elif in_64c_branch and stripped == "#else":
        in_64c_branch = False
    if not in_64c_branch:
        continue
    line_ending = "\n" if line.endswith("\n") else ""
    line_content = line.removesuffix(line_ending)
    for name, value in replacements.items():
        pattern = re.compile(
            rf"^(?P<prefix>\s*#define\s+{re.escape(name)}\s+\(?\s*)"
            r"\d+(?P<suffix>\s*\)?.*)$"
        )
        if match := pattern.match(line_content):
            lines[index] = (
                f"{match.group('prefix')}{value}{match.group('suffix')}"
                f"{line_ending}"
            )
            counts[name] += 1
            break
for name, count in counts.items():
    if count != 1:
        raise SystemExit(
            f"expected exactly one numeric definition for {name} in {header}; "
            f"found {count}"
        )
text = "".join(lines)
header.write_text(text, encoding="utf-8")
PYEOF
  log "Temporarily enabled enlarged cuPHY 64C limits in $limits_header"
}

if [[ "$do_build" == "1" || "$profile_rebuild" == "1" ]]; then
  banner "Build cubb_gpu_test_bench"
  if [[ "$limits_variant" == "enlarged" && "$dry_run" != "1" ]]; then
    apply_enlarged_cuphy_h_limits
  elif [[ "$limits_variant" == "enlarged" ]]; then
    log "[dry-run] would temporarily enable enlarged cuPHY 64C limits in $limits_header"
  fi
  run_cmd bash "$SDK_ROOT/testBenches/phase4_test_scripts/build_aerial_sdk.sh" \
    --targets cubb_gpu_test_bench --cuda-archs 80-real 90-real 100-real 120-real \
    -- -DCMAKE_BUILD_TYPE=Release -DENABLE_CUMAC="$enable_cumac" \
      -DENABLE_CUMAC_AIRAN="$enable_cumac_airan" -DENABLE_64C=ON
  if [[ "$dry_run" != "1" ]]; then
    printf '%s\n' "$limits_variant" > "$limits_variant_stamp"
  fi
fi

cd "$PERF_DIR"

# compare.py and the power plots import matplotlib, which the stock aerial
# container does not ship; without it the capacity-confirm step dies after
# the measurement succeeds. Install it up front like the manual perf scripts.
if ! python3 -c "import matplotlib" 2>/dev/null; then
  if [[ "$dry_run" == "1" ]]; then
    log "[dry-run] matplotlib missing; would install via pip"
  else
    log "matplotlib missing; installing via pip..."
    python3 -m pip install --quiet matplotlib \
      || echo "WARNING: matplotlib install failed; plot generation will fail" >&2
  fi
fi

banner "Step 1: ${function_cells}C functionality ref_check"
run_logged "$RUN_DIR/function_${function_cells}c.log" \
  python3 measure.py --yaml "$yaml_file" --target $smAllocation \
  --freq "$gpu_freq" --power "$gpu_power" --start "$function_cells" --cap "$function_cells" \
  --slots "$function_slots" --enable_ref_check

banner "Step 2: confirm latency cell capacity"
confirm_script=$(find_confirm_script)
if [[ "$dry_run" == "1" ]]; then
  log python3 "$confirm_script" --yaml "$yaml_file" --sm $smAllocation --start "$expected_capacity" \
    --freq "$gpu_freq" --power "$gpu_power" --slots "$confirm_slots" --output-dir "$RUN_DIR"
  cell_capacity="$expected_capacity"
else
  confirm_output=$(cd "$SDK_ROOT" && python3 "$confirm_script" \
    --yaml "$yaml_file" --sm $smAllocation --start "$expected_capacity" \
    --freq "$gpu_freq" --power "$gpu_power" --slots "$confirm_slots" \
    --output-dir "$RUN_DIR" 2>&1 | tee "$RUN_DIR/latency_confirm.log")
  cell_capacity=$(parse_cell_capacity "$confirm_output")
fi
echo "Confirmed cell capacity: $cell_capacity"

# Suggest a cicd_cases.json update when the confirmed capacity drifts from the
# seeded expected value. Only for an exact GPU match -- a fallback run is not a
# valid calibration of the detected card, so never suggest from it.
if [[ "$dry_run" == "0" && "$config_source" == "exact" && -n "$cell_capacity" \
      && "$cell_capacity" != "$expected_capacity" ]]; then
  echo "SUGGESTION: confirmed capacity differs from seeded value for $case_id/$matched_gpu_tag." >&2
  echo "  update cicd_cases.json: case $case_id gpu_configs.$matched_gpu_tag.expected_cell_capacity: $expected_capacity -> $cell_capacity" >&2
elif [[ "$dry_run" == "0" && "$config_source" == "fallback" ]]; then
  echo "NOTE: ran on fallback profile ($matched_gpu_tag); not suggesting a cicd_cases.json capacity update for an unrecognized GPU." >&2
fi

copy_if_exists "$PERF_DIR/$sweep_json" "$RUN_DIR/$sweep_json"
latency_swept_cells=$(json_cells_or_default "$RUN_DIR/$sweep_json" "$cell_capacity")
read -r -a latency_cell_array <<< "$latency_swept_cells"
mapfile -t latency_cell_keys < <(cell_keys "${latency_cell_array[@]}")
compare_files=()
for _ in "${latency_cell_keys[@]}"; do
  compare_files+=("$sweep_json")
done
run_cmd python3 compare.py --filenames "${compare_files[@]}" --cells "${latency_cell_keys[@]}"
latest_compare=$(ls -t compare-*.png 2>/dev/null | head -1 || true)
if [[ "$dry_run" == "0" && -n "$latest_compare" ]]; then
  cp "$latest_compare" "$RUN_DIR/latency_compare.png"
fi

banner "Step 3: power sweep ${power_start}..${cell_capacity}C"
run_logged "$RUN_DIR/power_sweep.log" \
  python3 measure.py --yaml "$yaml_file" --target $smAllocation \
  --freq "$gpu_freq" --power "$gpu_power" --start "$power_start" --cap "$cell_capacity" \
  --slots "$power_slots" --delay 0 --iterations "$power_iterations" --measure_power

power_summary="$RUN_DIR/power_per_cell.log"
if [[ "$dry_run" == "0" ]]; then
  : > "$power_summary"
fi
for ((cell=power_start; cell<=cell_capacity; cell++)); do
  cell_key="${cell}+0"
  log "python3 power.py --filenames $power_json --cells $cell_key"
  if [[ "$dry_run" == "0" ]]; then
    power_out=$(python3 power.py --filenames "$power_json" --cells "$cell_key" 2>&1) || true
    echo "[${cell}C] $power_out" | tee -a "$power_summary"
    copy_if_exists "$PERF_DIR/power.png" "$RUN_DIR/power_${cell}C.png"
  fi
  run_cmd python3 memory_plot.py --filenames "$power_json" --cells "$cell_key"
  if [[ "$dry_run" == "0" ]]; then
    copy_if_exists "$PERF_DIR/memory.png" "$RUN_DIR/memory_${cell}C.png"
  fi
  run_cmd python3 temperature_plot.py --filenames "$power_json" --cells "$cell_key"
  if [[ "$dry_run" == "0" ]]; then
    copy_if_exists "$PERF_DIR/temperature.png" "$RUN_DIR/temperature_${cell}C.png"
  fi
  if [[ -f clock_power_temperature_plot.py ]]; then
    run_cmd python3 clock_power_temperature_plot.py --filenames "$power_json" --cells "$cell_key"
    if [[ "$dry_run" == "0" ]]; then
      copy_if_exists "$PERF_DIR/clock_power_temperature.png" "$RUN_DIR/clock_power_temperature_${cell}C.png"
    fi
  fi
done
copy_if_exists "$PERF_DIR/$power_json" "$RUN_DIR/$power_json"

banner "Step 4: nsys trace at confirmed cell capacity ${cell_capacity}C"
nsys_cell="$cell_capacity"
if [[ "$dry_run" == "1" ]]; then
  run_logged "$RUN_DIR/nsys_${nsys_cell}C.log" \
    python3 measure.py --yaml "$yaml_file" --target $smAllocation \
    --freq "$gpu_freq" --power "$gpu_power" --start "$nsys_cell" --cap "$nsys_cell" \
    --slots "$nsys_slots" --delay "$nsys_delay" --iterations "$nsys_iterations" \
    --debug --debug_mode nsys --enable_nvprof
else
  before_list=$(mktemp)
  after_list=$(mktemp)
  find "$PERF_DIR" -maxdepth 1 -name '*.nsys-rep' -print | sort > "$before_list"
  run_logged "$RUN_DIR/nsys_${nsys_cell}C.log" \
    python3 measure.py --yaml "$yaml_file" --target $smAllocation \
    --freq "$gpu_freq" --power "$gpu_power" --start "$nsys_cell" --cap "$nsys_cell" \
    --slots "$nsys_slots" --delay "$nsys_delay" --iterations "$nsys_iterations" \
    --debug --debug_mode nsys --enable_nvprof
  find "$PERF_DIR" -maxdepth 1 -name '*.nsys-rep' -print | sort > "$after_list"
  new_rep=$(comm -13 "$before_list" "$after_list" | tail -1 || true)
  if [[ -z "$new_rep" ]]; then
    new_rep=$(ls -t "$PERF_DIR"/*.nsys-rep 2>/dev/null | head -1 || true)
  fi
  if [[ -n "$new_rep" ]]; then
    rep_base="${new_rep%.nsys-rep}"
    dest_base="$RUN_DIR/nsys/${fileNameStr}_${nsys_cell}C_${gpu_freq}MHz"
    for ext in nsys-rep sqlite qdstrm; do
      if [[ -f "${rep_base}.${ext}" ]]; then
        mv "${rep_base}.${ext}" "${dest_base}.${ext}"
      fi
    done
  fi
  rm -f "$before_list" "$after_list"
fi

if [[ "$dry_run" == "1" ]]; then
  log "[dry-run] would write $RUN_DIR/results.log"
else
  cat > "$RUN_DIR/results.log" <<RESULTS
case: $case_id
name: $case_name
delta: $case_delta
yaml: $yaml_file
freq_mhz: $gpu_freq
power_w: $gpu_power
sm_allocation: $smAllocation
expected_capacity: $expected_capacity
confirmed_capacity: $cell_capacity
latency_swept_cells: $latency_swept_cells
output_dir: $RUN_DIR
RESULTS
fi

echo
echo "======================================================================"
echo "RESULTS"
echo "======================================================================"
echo "  Case           : $case_id"
echo "  SM allocation  : $smAllocation"
echo "  Confirmed      : ${cell_capacity}C"
echo "  Latency cells  : $latency_swept_cells"
echo "  Output         : $RUN_DIR"
echo "======================================================================"
echo "Done."
'''


def load_database(path: Path) -> dict[str, Any]:
    """Load the CICD case database.

    Args:
        path (Path): JSON database path.

    Returns:
        dict[str, Any]: Parsed database containing a ``cases`` list.

    Raises:
        OSError: If the database file cannot be opened.
        json.JSONDecodeError: If the database file is not valid JSON.
        ValueError: If the parsed database does not contain a cases list.

    Examples:
        >>> database = load_database(DEFAULT_DB)
    """
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    if "cases" not in data or not isinstance(data["cases"], list):
        raise ValueError(f"{path} must contain a cases list")
    return data


def case_gpu_configs(case: dict[str, Any]) -> dict[str, dict[str, Any]]:
    """Read the per-GPU configuration map for a case.

    Args:
        case (dict[str, Any]): Case entry from the CICD database.

    Returns:
        dict[str, dict[str, Any]]: GPU tag to configuration mapping.

    Raises:
        ValueError: If ``gpu_configs`` is missing, empty, or not a dictionary.
        KeyError: If ``case_id`` is missing while reporting an invalid case.

    Examples:
        >>> configs = case_gpu_configs(database["cases"][0])
    """
    cfgs = case.get("gpu_configs")
    if not isinstance(cfgs, dict) or not cfgs:
        raise ValueError(
            f"case {case['case_id']} missing 'gpu_configs' map; "
            "schema v2 requires per-GPU freq/power/sm/expected entries"
        )
    return cfgs


def require_expected(case: dict[str, Any], gpu_tag: str) -> int:
    """Require the expected cell capacity for a GPU profile.

    Args:
        case (dict[str, Any]): Case entry from the CICD database.
        gpu_tag (str): GPU profile tag to inspect.

    Returns:
        int: Expected cell capacity for ``gpu_tag``.

    Raises:
        ValueError: If the GPU profile is missing or lacks expected capacity.
        KeyError: If required case metadata is missing while reporting errors.

    Examples:
        >>> expected = require_expected(database["cases"][0], "GH200")
    """
    cfgs = case_gpu_configs(case)
    cfg = cfgs.get(gpu_tag)
    if cfg is None:
        raise ValueError(
            f"case {case['case_id']} has no gpu_configs entry for {gpu_tag}"
        )
    expected = cfg.get("expected_cell_capacity")
    if expected is None:
        raise ValueError(
            f"case {case['case_id']}/{gpu_tag} has expected_cell_capacity=null; "
            "seed it before running confirm/power/nsys workflow"
        )
    return int(expected)


def case_to_runner_case(defaults: dict[str, Any], case: dict[str, Any]) -> list[dict[str, Any]]:
    """Convert a database case into runner manifest entries.

    Args:
        defaults (dict[str, Any]): Database default values.
        case (dict[str, Any]): Case entry to expand per GPU profile.

    Returns:
        list[dict[str, Any]]: Runner manifest case entries.

    Raises:
        FileNotFoundError: If the case YAML file does not exist.
        ValueError: If GPU configuration or numeric values are invalid.
        KeyError: If required case or GPU configuration fields are missing.

    Examples:
        >>> entries = case_to_runner_case(database.get("defaults", {}), database["cases"][0])
    """
    def get(name: str, fallback: Any = None) -> Any:
        return case.get(name, defaults.get(name, fallback))

    case_id = str(case["case_id"])
    yaml_path = (SCRIPT_DIR / case["yaml"]).resolve()
    if not yaml_path.is_file():
        raise FileNotFoundError(f"case {case_id} YAML not found: {yaml_path}")
    yaml_path, _ = _rewrite_yaml_for_arch(yaml_path)

    entries: list[dict[str, Any]] = []
    for gpu_tag, cfg in case_gpu_configs(case).items():
        entries.append({
            "id": f"{case_id}/{gpu_tag}",
            "case_id": case_id,
            "gpu": gpu_tag,
            "description": f"{case['long_name']} - {case['delta']}",
            "source_yaml": str(yaml_path),
            "raw_log": f"{DEFAULT_DB.name}:{case_id}:{gpu_tag}",
            "freq_mhz": int(cfg["freq_mhz"]),
            "power_w": int(cfg["power_w"]),
            "sm": [str(x) for x in cfg["sm_allocation"]],
            "expected_capacity": require_expected(case, gpu_tag),
            "usecase": get("usecase", "F08"),
            "function_slots": int(get("function_slots", 20)),
            "confirm_slots": int(get("confirm_slots", 300)),
            "power_start": int(get("power_start", 1)),
            "power_slots": int(get("power_slots", 10)),
            "power_iterations": int(get("power_iterations", 2000)),
            "nsys_slots": int(get("nsys_slots", 10)),
            "nsys_delay": int(get("nsys_delay", 10000)),
            "nsys_iterations": int(get("nsys_iterations", 1)),
            "setup_once": bool(get("setup_once", True)),
            "nsys_extra_args": list(get("nsys_extra_args", [])),
        })
    return entries


def write_runner_manifest(database: dict[str, Any], path: Path) -> Path:
    """Write a resolved runner manifest.

    Args:
        database (dict[str, Any]): Parsed CICD case database.
        path (Path): Destination manifest path.

    Returns:
        Path: Path to the written manifest.

    Raises:
        OSError: If the destination directory or file cannot be written.
        FileNotFoundError: If a referenced case YAML file does not exist.
        ValueError: If a case cannot be converted into runner entries.
        KeyError: If required database fields are missing.

    Examples:
        >>> manifest = write_runner_manifest(database, GENERATED_DIR / "cicd_manifest.json")
    """
    defaults = database.get("defaults", {})
    cases: list[dict[str, Any]] = []
    for case in database["cases"]:
        cases.extend(case_to_runner_case(defaults, case))
    manifest = {"defaults": {}, "cases": cases}
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return path


def find_case(database: dict[str, Any], case_id: str) -> dict[str, Any]:
    """Find a case by ID.

    Args:
        database (dict[str, Any]): Parsed CICD case database.
        case_id (str): Case ID to locate.

    Returns:
        dict[str, Any]: Matching case entry.

    Raises:
        ValueError: If no case matches ``case_id``.
        KeyError: If required database or case fields are missing.

    Examples:
        >>> case = find_case(database, "80001")
    """
    for case in database["cases"]:
        if str(case["case_id"]) == str(case_id):
            return case
    raise ValueError(f"unknown case id: {case_id}")


def case_enabled(case: dict[str, Any]) -> bool:
    """Return whether a case is enabled.

    Args:
        case (dict[str, Any]): Case entry from the CICD database.

    Returns:
        bool: The case's ``enabled`` flag; a missing flag defaults to True.

    Raises:
        ValueError: If ``enabled`` is present but is not a boolean.

    Examples:
        >>> case_enabled({"case_id": "80001", "enabled": True})
        True
    """
    enabled = case.get("enabled", True)
    if not isinstance(enabled, bool):
        raise ValueError(
            f"case {case.get('case_id', '<unknown>')} has non-boolean enabled={enabled!r}"
        )
    return enabled


def _frequency_config(cfg: dict[str, Any], freq_mhz: int | None) -> dict[str, Any]:
    """Return the requested frequency overlay, or the default GPU profile.

    Args:
        cfg (dict[str, Any]): GPU configuration with optional alternate
            frequency profiles.
        freq_mhz (int | None): Alternate GPU frequency profile to select, or
            None for the default profile.

    Returns:
        dict[str, Any]: Selected GPU configuration overlay.
    """
    if freq_mhz is None or int(cfg.get("freq_mhz", -1)) == freq_mhz:
        return cfg
    alt = cfg.get("alt_freqs", {}).get(str(freq_mhz))
    if alt is None:
        return cfg
    return {**cfg, **alt}


def render_gpu_config_cases(case: dict[str, Any], freq_mhz: int | None = None) -> str:
    """Render exact-match shell branches for GPU profiles.

    Args:
        case (dict[str, Any]): Case entry from the CICD database.
        freq_mhz (int | None): Alternate GPU frequency profile to select, or
            None for the default profile.

    Returns:
        str: Shell ``case`` branches for configured GPU tags.

    Raises:
        ValueError: If GPU configuration or expected capacity is invalid.
        KeyError: If required GPU configuration fields are missing.

    Examples:
        >>> shell_cases = render_gpu_config_cases(database["cases"][0])
    """
    lines: list[str] = []
    for gpu_tag, base_cfg in case_gpu_configs(case).items():
        cfg = _frequency_config(base_cfg, freq_mhz)
        sm = " ".join(str(x) for x in cfg["sm_allocation"])
        freq = int(cfg["freq_mhz"])
        power = int(cfg["power_w"])
        expected = cfg.get("expected_cell_capacity")
        if expected is None:
            raise ValueError(
                f"case {case['case_id']}/{gpu_tag} has expected_cell_capacity=null"
            )
        expected = int(expected)
        gc = cfg.get("green_context_sm_alloc") or {}
        gc_json = json.dumps(gc, separators=(",", ":")) if gc else ""
        enlarge_cuphy_h_limits = cfg.get("enlarge_cuphy_h_limits", False)
        if not isinstance(enlarge_cuphy_h_limits, bool):
            raise ValueError(
                f"case {case['case_id']} GPU profile {gpu_tag} has non-boolean "
                f"enlarge_cuphy_h_limits={enlarge_cuphy_h_limits!r}"
            )
        lines.append(f"  {gpu_tag})")
        lines.append(f'    config_source="exact"')
        lines.append(f'    matched_gpu_tag="{gpu_tag}"')
        lines.append(f'    smAllocation="{sm}"')
        lines.append(f'    gpu_freq="{freq}"')
        lines.append(f'    gpu_power="{power}"')
        lines.append(f'    expected_capacity="{expected}"')
        lines.append(f'    enlarge_cuphy_h_limits="{"ON" if enlarge_cuphy_h_limits else "OFF"}"')
        lines.append(f"    gc_sm_alloc='{gc_json}'")
        lines.append("    ;;")
    return "\n".join(lines)


def render_fallback_branch(
    case: dict[str, Any], fallback_gpu: str, freq_mhz: int | None = None
) -> str:
    """Render the fallback shell branch for an unrecognized GPU.

    Args:
        case (dict[str, Any]): Case entry from the CICD database.
        fallback_gpu (str): GPU profile tag to use as fallback.
        freq_mhz (int | None): Alternate GPU frequency profile to select, or
            None for the default profile.

    Returns:
        str: Shell commands for fallback selection or hard failure.

    Raises:
        ValueError: If GPU configuration or expected capacity is invalid.
        KeyError: If required case or GPU configuration fields are missing.

    Examples:
        >>> branch = render_fallback_branch(database["cases"][0], "RTX_PRO_4500")
    """
    cfgs = case_gpu_configs(case)
    base_cfg = cfgs.get(fallback_gpu)
    if base_cfg is None:
        return "\n".join([
            f'    echo "ERROR: case $case_id has no gpu_configs entry for detected GPU '
            f"'$detected_gpu' (tag $detected_gpu_tag), and no '{fallback_gpu}' fallback.\" >&2",
            '    echo "       Supported GPUs: $supported_gpus" >&2',
            "    exit 1",
        ])
    cfg = _frequency_config(base_cfg, freq_mhz)
    sm = " ".join(str(x) for x in cfg["sm_allocation"])
    freq = int(cfg["freq_mhz"])
    power = int(cfg["power_w"])
    expected = cfg.get("expected_cell_capacity")
    if expected is None:
        raise ValueError(
            f"case {case['case_id']}/{fallback_gpu} has expected_cell_capacity=null"
        )
    expected = int(expected)
    gc = cfg.get("green_context_sm_alloc") or {}
    gc_json = json.dumps(gc, separators=(",", ":")) if gc else ""
    enlarge_cuphy_h_limits = cfg.get("enlarge_cuphy_h_limits", False)
    if not isinstance(enlarge_cuphy_h_limits, bool):
        raise ValueError(
            f"case {case['case_id']} GPU profile {fallback_gpu} has non-boolean "
            f"enlarge_cuphy_h_limits={enlarge_cuphy_h_limits!r}"
        )
    return "\n".join([
        f'    echo "WARNING: unrecognized GPU \'$detected_gpu\' (tag $detected_gpu_tag); '
        f'falling back to {fallback_gpu} profile -- SM/freq/power/capacity may not be optimal" >&2',
        f'    config_source="fallback"',
        f'    matched_gpu_tag="{fallback_gpu}"',
        f'    smAllocation="{sm}"',
        f'    gpu_freq="{freq}"',
        f'    gpu_power="{power}"',
        f'    expected_capacity="{expected}"',
        f'    enlarge_cuphy_h_limits="{"ON" if enlarge_cuphy_h_limits else "OFF"}"',
        f"    gc_sm_alloc='{gc_json}'",
    ])


def write_offline_script(
    case: dict[str, Any],
    defaults: dict[str, Any],
    *,
    slots_override: int | None = None,
    freq_mhz: int | None = None,
) -> Path:
    """Write a standalone offline script for one case.

    Args:
        case (dict[str, Any]): Case entry from the CICD database.
        defaults (dict[str, Any]): Database default values.
        slots_override (int | None): Optional confirm-slot override.
        freq_mhz (int | None): Alternate GPU frequency profile to select, or
            None for the default profile.

    Returns:
        Path: Path to the generated executable shell script.

    Raises:
        OSError: If the script cannot be written or chmodded.
        ValueError: If GPU configuration or expected capacity is invalid.
        KeyError: If required case fields are missing.

    Examples:
        >>> script = write_offline_script(database["cases"][0], database.get("defaults", {}))
    """
    case_id = str(case["case_id"])
    script = SCRIPT_DIR / f"cubb_gpu_test_{case_id}.sh"

    def get(name: str, fallback: Any = None) -> Any:
        return case.get(name, defaults.get(name, fallback))

    confirm_slots = slots_override if slots_override is not None else get("confirm_slots", 300)
    enable_cumac = get("mac", False)
    if not isinstance(enable_cumac, bool):
        raise ValueError(f"case {case_id} has non-boolean mac={enable_cumac!r}")
    enable_cumac_airan = get("cumac_airan", False)
    if not isinstance(enable_cumac_airan, bool):
        raise ValueError(
            f"case {case_id} has non-boolean cumac_airan={enable_cumac_airan!r}"
        )
    if enable_cumac_airan and not enable_cumac:
        raise ValueError(f"case {case_id} enables cumac_airan without mac")
    supported = ", ".join(case_gpu_configs(case).keys())
    fallback_gpu = str(get("fallback_gpu", "RTX_PRO_4500"))
    yaml_path = (SCRIPT_DIR / case["yaml"]).resolve()
    _, yaml_rel = _rewrite_yaml_for_arch(yaml_path)
    values = {
        "@@CASE_ID@@": case_id,
        "@@LONG_NAME@@": str(case["long_name"]),
        "@@DELTA@@": str(case["delta"]),
        "@@YAML_FILE@@": yaml_rel,
        "@@USECASE@@": str(get("usecase", "F08")),
        "@@GC_SUFFIX@@": "_gc" if get("use_green_contexts", False) else "",
        "@@SUPPORTED_GPUS@@": supported,
        "@@ENABLE_CUMAC@@": "ON" if enable_cumac else "OFF",
        "@@ENABLE_CUMAC_AIRAN@@": "ON" if enable_cumac_airan else "OFF",
        "@@FALLBACK_GPU@@": fallback_gpu,
        "@@GPU_CONFIG_CASES@@": render_gpu_config_cases(case, freq_mhz),
        "@@FALLBACK_BRANCH@@": render_fallback_branch(case, fallback_gpu, freq_mhz),
        "@@FUNCTION_SLOTS@@": str(get("function_slots", 20)),
        "@@FUNCTION_CELLS@@": str(get("function_cells", 2)),
        "@@CONFIRM_SLOTS@@": str(confirm_slots),
        "@@POWER_START@@": str(get("power_start", 1)),
        "@@POWER_SLOTS@@": str(get("power_slots", 10)),
        "@@POWER_ITERATIONS@@": str(get("power_iterations", 2000)),
        "@@NSYS_SLOTS@@": str(get("nsys_slots", 10)),
        "@@NSYS_DELAY@@": str(get("nsys_delay", 10000)),
        "@@NSYS_ITERATIONS@@": str(get("nsys_iterations", 1)),
    }
    text = OFFLINE_SCRIPT_TEMPLATE
    for placeholder, value in values.items():
        text = text.replace(placeholder, value)
    script.write_text(text, encoding="utf-8")
    script.chmod(0o755)
    return script


def write_selected_offline_scripts(
    database: dict[str, Any],
    case_selector: str,
    *,
    slots_override: int | None = None,
    include_disabled: bool = False,
    freq_mhz: int | None = None,
) -> list[Path]:
    """Write offline scripts for selected cases.

    Args:
        database (dict[str, Any]): Parsed CICD case database.
        case_selector (str): Case ID to generate, or ``all``.
        slots_override (int | None): Optional confirm-slot override.
        include_disabled (bool): With ``all``, also select cases marked
            ``enabled: false``. An explicit case ID is always selected.
        freq_mhz (int | None): Alternate GPU frequency profile to select, or
            None for the default profile.

    Returns:
        list[Path]: Paths to generated shell scripts.

    Raises:
        ValueError: If a selected case or GPU configuration is invalid.
        OSError: If a selected script cannot be written or chmodded.
        KeyError: If required database or case fields are missing.

    Examples:
        >>> scripts = write_selected_offline_scripts(database, "all")
    """
    defaults = database.get("defaults", {})
    if case_selector == "all":
        selected = list(database["cases"])
        if not include_disabled:
            skipped = [c for c in selected if not case_enabled(c)]
            if skipped:
                skipped_ids = ", ".join(str(c["case_id"]) for c in skipped)
                print(f"Skipping disabled case(s) {skipped_ids} "
                      "(pass --include-disabled to select them)")
            selected = [c for c in selected if case_enabled(c)]
    else:
        selected = [find_case(database, case_selector)]
        for case in selected:
            if not case_enabled(case):
                print(f"NOTE: case {case['case_id']} is marked enabled: false in "
                      "cicd_cases.json; selecting it anyway because it was requested explicitly")
    return [
        write_offline_script(
            case, defaults, slots_override=slots_override, freq_mhz=freq_mhz
        )
        for case in selected
    ]


def list_cases(database: dict[str, Any]) -> None:
    """Print the configured CICD cases.

    Args:
        database (dict[str, Any]): Parsed CICD case database.

    Returns:
        None: This function prints the case table.

    Raises:
        KeyError: If required database or case fields are missing.

    Examples:
        >>> list_cases(database)
    """
    defaults = database.get("defaults", {})
    print("case   gpu             expected  freq/power      sm allocation              yaml")
    print("-----  --------------  --------  --------------  -------------------------  -------------------------------")
    for case in database["cases"]:
        cfgs = case.get("gpu_configs") or {}
        if not cfgs:
            print(f"{case['case_id']}  (no gpu_configs)                                                  {case['yaml']}")
            continue
        first = True
        for gpu_tag, cfg in cfgs.items():
            expected = cfg.get("expected_cell_capacity")
            expected_text = "TBD" if expected is None else f"{expected}C"
            sm_text = " ".join(str(x) for x in cfg.get("sm_allocation", []))
            fp_text = f"{cfg.get('freq_mhz','?')}MHz/{cfg.get('power_w','?')}W"
            cid = case["case_id"] if first else ""
            yaml_text = case["yaml"] if first else ""
            if first and not case_enabled(case):
                yaml_text = f"{yaml_text}  [disabled]"
            print(f"{cid:5s}  {gpu_tag:14s}  {expected_text:>8}  {fp_text:14s}  {sm_text:25s}  {yaml_text}")
            first = False
        print(f"       {case['long_name']}")
        print(f"       {case['delta']}")
    status = defaults.get("expected_capacity_status")
    if status:
        print(f"\nexpected_capacity_status: {status}")


def runner_manifest_path(args: argparse.Namespace) -> Path:
    """Resolve the runner manifest path.

    Args:
        args (argparse.Namespace): Parsed command-line arguments.

    Returns:
        Path: Explicit generated manifest path or the default generated path.

    Raises:
        AttributeError: If ``args`` does not define ``generated_manifest``.
        OSError: If path resolution fails for the explicit manifest path.

    Examples:
        >>> path = runner_manifest_path(argparse.Namespace(generated_manifest=None))
    """
    if args.generated_manifest:
        return Path(args.generated_manifest).resolve()
    return GENERATED_DIR / "cicd_manifest.json"


def invoke_runner(args: argparse.Namespace, database: dict[str, Any]) -> int:
    """Run generated offline scripts for selected cases.

    Args:
        args (argparse.Namespace): Parsed command-line arguments for a run.
        database (dict[str, Any]): Parsed CICD case database.

    Returns:
        int: First nonzero script exit code, or 0 when all scripts pass.

    Raises:
        ValueError: If ``--sdk-root`` is not a valid SDK root or cases are invalid.
        OSError: If script generation or subprocess launch fails.
        KeyError: If required argument, database, or case fields are missing.

    Examples:
        >>> rc = invoke_runner(args, database)
    """
    sdk_root = Path(getattr(args, "sdk_root", PROJECT_ROOT)).resolve()
    marker = sdk_root / "testBenches" / "perf" / "measure.py"
    if not marker.is_file():
        raise ValueError(f"--sdk-root is not a valid SDK root: {sdk_root}")

    include_disabled = getattr(args, "include_disabled", False)
    cumac_onnx_name = selected_cumac_onnx_name(
        database,
        args.case,
        include_disabled=include_disabled,
    )
    if cumac_onnx_name is not None:
        prepare_cumac_onnx(
            sdk_root,
            cumac_onnx_name,
            overwrite=getattr(args, "overwrite_onnx", False),
            dry_run=getattr(args, "dry_run", False),
            bootstrap=getattr(args, "bootstrap_venv", False),
        )

    slots_override = getattr(args, "slots", None)
    scripts = write_selected_offline_scripts(
        database,
        args.case,
        slots_override=slots_override,
        include_disabled=include_disabled,
        freq_mhz=getattr(args, "freq_mhz", None),
    )
    script_args: list[str] = []
    if getattr(args, "build", False):
        script_args.append("--build")
    if getattr(args, "dry_run", False):
        script_args.append("--dry-run")
    if slots_override is not None:
        script_args.extend(["--slots", str(slots_override)])
    if args.output_root:
        script_args.extend(["--output-root", str(Path(args.output_root).resolve())])
    if args.run_id:
        script_args.extend(["--run-id", args.run_id])
    if getattr(args, "resume", False):
        print("WARNING: --resume is not supported by generated standalone scripts; ignoring")
    if getattr(args, "strict_expected", False):
        print("WARNING: --strict-expected is not supported by generated standalone scripts; ignoring")

    rc = 0
    env = os.environ.copy()
    env["cuBB_SDK"] = str(sdk_root)
    for script in scripts:
        print(f"offline run script: {script}", flush=True)
        result = subprocess.run([str(script), *script_args], cwd=str(sdk_root), env=env)
        if result.returncode != 0:
            rc = result.returncode
            break
    return rc


def case_cumac_onnx_name(case: dict[str, Any]) -> str:
    """Read the cuMAC ONNX filename from a case's YAML configuration.

    Args:
        case (dict[str, Any]): Case entry from the CICD database.

    Returns:
        str: Basename of ``cumac_options.airan.model_path``.

    Raises:
        FileNotFoundError: If the case YAML does not exist.
        ValueError: If the YAML or ONNX model path is invalid.
        KeyError: If required case metadata is missing.

    Examples:
        >>> case = {"case_id": "80021", "yaml": "cubb_gpu_test_config_80021.yaml"}
        >>> case_cumac_onnx_name(case)
        'mlp_4x512_relu.onnx'
    """
    case_id = str(case["case_id"])
    yaml_path = (SCRIPT_DIR / case["yaml"]).resolve()
    if not yaml_path.is_file():
        raise FileNotFoundError(f"case {case_id} YAML not found: {yaml_path}")
    try:
        data = yaml.safe_load(yaml_path.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError as err:
        raise ValueError(f"case {case_id} YAML is invalid: {yaml_path}: {err}") from err

    config = data.get("config", {})
    for scope in (data, config):
        cumac_options = scope.get("cumac_options", {})
        model_path = cumac_options.get("airan", {}).get("model_path")
        if model_path:
            name = Path(str(model_path)).name
            if not name.lower().endswith(".onnx"):
                raise ValueError(
                    f"case {case_id} cuMAC AIRAN model is not an ONNX file: {model_path}"
                )
            return name
    raise ValueError(
        f"case {case_id} YAML missing config.cumac_options.airan.model_path: {yaml_path}"
    )


def selected_cumac_onnx_name(
    database: dict[str, Any],
    case_selector: str,
    *,
    include_disabled: bool = False,
) -> str | None:
    """Return the ONNX filename required by selected ``8002x`` cases.

    Args:
        database (dict[str, Any]): Parsed CICD case database.
        case_selector (str): Explicit case ID, or ``all``.
        include_disabled (bool): With ``all``, include disabled cases.

    Returns:
        str | None: Shared ONNX filename, or None when no selected case needs it.

    Raises:
        ValueError: If a case is unknown, has an invalid model path, or selected
            ``8002x`` cases do not use the same ONNX filename.
        FileNotFoundError: If a selected case YAML does not exist.
        KeyError: If required case metadata is missing.

    Examples:
        >>> selected_cumac_onnx_name(database, "80021")
        'mlp_4x512_relu.onnx'
    """
    if case_selector == "all":
        selected = [
            case
            for case in database["cases"]
            if include_disabled or case_enabled(case)
        ]
    else:
        selected = [find_case(database, case_selector)]
    names = {
        case_cumac_onnx_name(case)
        for case in selected
        if str(case["case_id"]).startswith(CUMAC_ONNX_CASE_PREFIX)
    }
    if len(names) > 1:
        raise ValueError(
            "selected 8002x cases require different cuMAC ONNX models: "
            + ", ".join(sorted(names))
        )
    return next(iter(names), None)


# Import names for the dependencies installed by cuMAC/setup_venv.sh (pyyaml
# imports as ``yaml``); used to confirm an interpreter can generate the model.
_CUMAC_ONNX_IMPORTS = "import torch, onnx, yaml, numpy"


def _cumac_deps_importable(python: Path) -> bool:
    """Return True if ``python`` can import the pinned cuMAC ONNX deps.

    Args:
        python (Path): Interpreter to probe.

    Returns:
        bool: True when every dependency imports cleanly.
    """
    probe = subprocess.run(
        [str(python), "-c", _CUMAC_ONNX_IMPORTS],
        capture_output=True,
        text=True,
    )
    return probe.returncode == 0


def bootstrap_cumac_venv(sdk_root: Path, *, dry_run: bool = False) -> Path:
    """Create the cuMAC model-generation venv using its canonical setup script.

    Only invoked when ``--bootstrap-venv`` is passed. Keeping installation in
    ``cuMAC/setup_venv.sh`` ensures this runner uses the Aerial-container Python
    version and exactly the same package pins as manual model generation.

    Args:
        sdk_root (Path): Aerial SDK checkout root.
        dry_run (bool): Print the actions without creating or installing.

    Returns:
        Path: Path to the venv python interpreter.

    Raises:
        FileNotFoundError: If the canonical setup script is unavailable.
        subprocess.CalledProcessError: If venv creation or dependency installation fails.
        RuntimeError: If the deps still do not import after installation.

    Examples:
        >>> bootstrap_cumac_venv(sdk_root, dry_run=True)  # doctest: +SKIP
    """
    venv_dir = sdk_root / "cuMAC" / ".venv"
    python = venv_dir / "bin" / "python"
    setup_script = sdk_root / "cuMAC" / "setup_venv.sh"
    # A present interpreter is not proof of a usable venv: a failed install can
    # leave .venv/bin/python behind. Only skip provisioning when the deps import.
    if not dry_run and python.is_file() and _cumac_deps_importable(python):
        return python
    if not setup_script.is_file():
        raise FileNotFoundError(f"cuMAC venv setup script not found: {setup_script}")
    if dry_run:
        print(f"[dry-run] bootstrap cuMAC model-generation venv: {setup_script}")
        return python
    print(f"Bootstrapping cuMAC model-generation venv at {venv_dir} ...", flush=True)
    environment = os.environ.copy()
    environment.setdefault("BASE_PYTHON", sys.executable)
    subprocess.run(
        [str(setup_script)],
        cwd=str(sdk_root),
        check=True,
        env=environment,
    )
    if not python.is_file():
        raise RuntimeError(
            f"cuMAC model-generation venv python not found after running "
            f"cuMAC/setup_venv.sh: {python}"
        )
    if not _cumac_deps_importable(python):
        raise RuntimeError(
            f"cuMAC model-generation venv at {venv_dir} still cannot import the cuMAC ONNX deps "
            "after running cuMAC/setup_venv.sh"
        )
    return python


def resolve_cumac_python(
    sdk_root: Path,
    *,
    bootstrap: bool = False,
    dry_run: bool = False,
) -> Path:
    """Select an interpreter that can generate the cuMAC ONNX model.

    The interpreter running this command is preferred when the required
    packages are installed system-wide. Otherwise, reuse the dedicated cuMAC
    venv or create it when ``bootstrap`` is enabled.

    Args:
        sdk_root (Path): Aerial SDK checkout root.
        bootstrap (bool): Create the dedicated venv when no usable interpreter exists.
        dry_run (bool): Print bootstrap actions without installing packages.

    Returns:
        Path: Python interpreter to use for model generation.

    Raises:
        FileNotFoundError: If neither the current interpreter nor the cuMAC venv is usable.

    Examples:
        >>> python = resolve_cumac_python(sdk_root)  # doctest: +SKIP
        >>> python.is_file()  # doctest: +SKIP
        True
    """
    current_python = Path(sys.executable)
    if _cumac_deps_importable(current_python):
        print(f"Using current Python for cuMAC ONNX generation: {current_python}")
        return current_python

    venv_python = sdk_root / "cuMAC" / ".venv" / "bin" / "python"
    if venv_python.is_file() and _cumac_deps_importable(venv_python):
        print(f"Using cuMAC venv for ONNX generation: {venv_python}")
        return venv_python

    if bootstrap:
        return bootstrap_cumac_venv(sdk_root, dry_run=dry_run)

    raise FileNotFoundError(
        "cuMAC ONNX dependencies are unavailable in the current Python "
        f"({current_python}) and the cuMAC virtualenv ({venv_python}). "
        f"Create it with `{sdk_root / 'cuMAC' / 'setup_venv.sh'}`, or re-run "
        "with --bootstrap-venv."
    )


def prepare_cumac_onnx(
    sdk_root: Path,
    onnx_name: str,
    *,
    overwrite: bool = False,
    dry_run: bool = False,
    bootstrap: bool = False,
) -> Path:
    """Generate the cuMAC ONNX model directly in ``testVectors`` when needed.

    Args:
        sdk_root (Path): Aerial SDK checkout root.
        onnx_name (str): ONNX basename read from the selected case YAML.
        overwrite (bool): Regenerate an existing ONNX model.
        dry_run (bool): Print the action without generating files.
        bootstrap (bool): If no usable Python is available, create the cuMAC
            model-generation venv and install the pinned dependencies.

    Returns:
        Path: Destination ONNX path.

    Raises:
        FileNotFoundError: If the generator or a usable Python environment is unavailable.
        RuntimeError: If generation succeeds without producing a fresh ONNX.
        subprocess.CalledProcessError: If model generation fails.

    Examples:
        >>> target = prepare_cumac_onnx(
        ...     sdk_root, "mlp_4x512_relu.onnx", dry_run=True
        ... )
        >>> target == sdk_root / "testVectors" / "mlp_4x512_relu.onnx"
        True
    """
    target_dir = sdk_root / "testVectors"
    target = target_dir / onnx_name
    if target.is_file() and not overwrite:
        print(f"cuMAC ONNX already exists; reusing {target}")
        return target

    generator = sdk_root / "cuMAC" / "examples" / "ml" / "trtEngine" / "gen_models.py"
    if not generator.is_file():
        raise FileNotFoundError(f"cuMAC model generator not found: {generator}")

    python = resolve_cumac_python(
        sdk_root,
        bootstrap=bootstrap,
        dry_run=dry_run,
    )

    command = [
        str(python),
        str(generator),
        "-o",
        str(target_dir),
        "--no-clean",
        "--no-inf-config",
        "--no-pdf",
    ]
    action = "overwriting" if target.is_file() else "generating"
    if dry_run:
        print(f"[dry-run] {action} cuMAC ONNX: {' '.join(command)}")
        return target

    target_dir.mkdir(parents=True, exist_ok=True)
    previous_mtime_ns = target.stat().st_mtime_ns if target.is_file() else None
    print(f"{action.capitalize()} cuMAC ONNX: {target}", flush=True)
    subprocess.run(command, cwd=str(sdk_root), check=True)
    if not target.is_file():
        raise RuntimeError(f"cuMAC model generator did not produce {target}")
    if previous_mtime_ns is not None and target.stat().st_mtime_ns == previous_mtime_ns:
        raise RuntimeError(f"cuMAC model generator did not refresh {target}")
    return target


def add_run_args(parser: argparse.ArgumentParser, *, suppress_defaults: bool = False) -> None:
    """Add common run arguments to an argument parser.

    Args:
        parser (argparse.ArgumentParser): Parser to modify.
        suppress_defaults (bool): Whether to suppress defaults for subparsers.

    Returns:
        None: The parser is modified in place.

    Raises:
        argparse.ArgumentError: If an added option conflicts with an existing option.

    Examples:
        >>> parser = argparse.ArgumentParser()
        >>> add_run_args(parser)
    """
    default = argparse.SUPPRESS if suppress_defaults else None
    bool_default = argparse.SUPPRESS if suppress_defaults else False
    parser.add_argument("--case", default=default, help="Case id, or all")
    parser.add_argument(
        "--sdk-root",
        default=argparse.SUPPRESS if suppress_defaults else str(PROJECT_ROOT),
        help="SDK root",
    )
    parser.add_argument("--output-root", default=default, help="Default: cicd_cases/runs")
    parser.add_argument("--run-id", default=default, help="Run id directory name")
    parser.add_argument(
        "--slots",
        type=int,
        default=default,
        help="Override confirm_cell_capacity.py slots from cicd_cases.json",
    )
    parser.add_argument(
        "--freq-mhz",
        type=int,
        default=default,
        help="Use a matching gpu_configs.alt_freqs entry when available",
    )
    parser.add_argument("--build", action="store_true", default=bool_default, help="Build before running")
    parser.add_argument("--resume", action="store_true", default=bool_default, help="Resume from run_state.json")
    parser.add_argument("--dry-run", action="store_true", default=bool_default, help="Print commands only")
    parser.add_argument(
        "--overwrite-onnx",
        action="store_true",
        default=bool_default,
        help="Regenerate the 8002x cuMAC ONNX model even when it already exists",
    )
    parser.add_argument(
        "--bootstrap-venv",
        "--bootstrap_venv",
        action="store_true",
        default=bool_default,
        dest="bootstrap_venv",
        help="If the current Python lacks the cuMAC ONNX deps, create a dedicated venv and "
             "pip-install the pinned torch/onnx/pyyaml packages. Off by default; only affects "
             "AI-RAN cases (80021/80023).",
    )
    parser.add_argument(
        "--script-only",
        "--script_only",
        action="store_true",
        default=bool_default,
        dest="script_only",
        help="Only generate offline per-case shell script(s); do not run tests",
    )
    parser.add_argument(
        "--strict-expected",
        action="store_true",
        default=bool_default,
        help="Fail on capacity drift",
    )
    parser.add_argument(
        "--include-disabled",
        "--include_disabled",
        action="store_true",
        default=bool_default,
        dest="include_disabled",
        help="With --case all, also select cases marked enabled: false in cicd_cases.json",
    )


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments for the CICD runner.

    Args:
        None.

    Returns:
        argparse.Namespace: Parsed command-line arguments.

    Raises:
        SystemExit: If argparse handles ``--help`` or invalid arguments.

    Examples:
        CLI:
            $ python3 run_cicd_cases.py list
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--db", default=str(DEFAULT_DB), help="CICD case database JSON")
    parser.add_argument("--generated-manifest", default=None, help=argparse.SUPPRESS)
    add_run_args(parser)

    sub = parser.add_subparsers(dest="cmd")

    sub.add_parser("list", help="List CICD cases from cicd_cases.json")
    sub.add_parser("manifest", help="Write a resolved case manifest JSON and exit")
    p_scripts = sub.add_parser("scripts", help="Generate offline per-case shell scripts")
    p_scripts.add_argument("--case", default="all", help="Case id, or all")
    p_scripts.add_argument(
        "--slots",
        type=int,
        default=None,
        help="Override confirm_cell_capacity.py slots in generated scripts",
    )
    p_scripts.add_argument(
        "--include-disabled",
        "--include_disabled",
        action="store_true",
        default=False,
        dest="include_disabled",
        help="With --case all, also generate scripts for cases marked enabled: false",
    )

    p_run = sub.add_parser("run", help="Run one CICD case or all cases")
    add_run_args(p_run, suppress_defaults=True)

    return parser.parse_args()


def main() -> None:
    """Run the CICD command-line entry point.

    Args:
        None.

    Returns:
        None: This function dispatches commands and prints command output.

    Raises:
        SystemExit: If a run command returns an exit code or command dispatch fails.
        OSError: If the database, manifest, scripts, or subprocesses cannot be accessed.
        ValueError: If the database or selected cases are invalid.
        FileNotFoundError: If a referenced case YAML file does not exist.
        json.JSONDecodeError: If the database file is not valid JSON.

    Examples:
        CLI:
            $ python3 run_cicd_cases.py run --case 80001 --dry-run
    """
    args = parse_args()
    database = load_database(Path(args.db))

    if args.cmd is None:
        args.cmd = "run" if args.case else "list"
    if args.cmd == "run" and args.case is None:
        args.case = "all"

    if args.cmd == "list":
        list_cases(database)
        return

    if args.cmd == "scripts":
        for script in write_selected_offline_scripts(
            database,
            args.case,
            slots_override=args.slots,
            include_disabled=getattr(args, "include_disabled", False),
        ):
            print(script)
        return

    if args.cmd == "run" and getattr(args, "script_only", False):
        for script in write_selected_offline_scripts(
            database,
            args.case,
            slots_override=getattr(args, "slots", None),
            include_disabled=getattr(args, "include_disabled", False),
        ):
            print(script)
        return

    manifest = write_runner_manifest(database, runner_manifest_path(args))
    if args.cmd == "manifest":
        print(manifest)
        return

    if args.cmd == "run":
        raise SystemExit(invoke_runner(args, database))

    raise SystemExit(f"unknown command: {args.cmd}")


if __name__ == "__main__":
    main()
